//! In-memory emission of generated source, plus `rustfmt` normalization.
//!
//! Emission is pure: it maps a validated [`Spec`] + [`PacketSpec`] to a sorted
//! `BTreeMap<PathBuf, String>` of *relative* paths to raw source. Normalization
//! then runs the real `rustfmt` over each `.rs` file and enforces LF endings
//! with a single trailing newline. Both `generate` and `--check` go through
//! this exact path, so they can never disagree.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use crate::error::GenError;
use crate::packets::{
    group_digits, Direction, Field, PacketDef, PacketSpec, State, StructDef, WireType,
};
use crate::spec::{Spec, MINECRAFT_VERSION};

/// The mandatory first line of every generated file.
///
/// Kept byte-exact: tooling and reviewers key off it to refuse hand edits.
pub(crate) const GENERATED_HEADER: &str =
    "// @generated by ferrumc-proto-gen. Do not edit by hand.";

/// The four connection states M06 covers, in protocol-progression order.
const STATES: [State; 4] = [
    State::Handshake,
    State::Status,
    State::Login,
    State::Configuration,
];

/// Emits every generated file as `relative path -> raw (un-normalized) source`.
///
/// Output order is kept deterministic by the `BTreeMap` (and by sorting inside
/// the [`PacketSpec`] itself), so `generate` and `--check` always agree.
pub(crate) fn emit(spec: &Spec, packets: &PacketSpec) -> BTreeMap<PathBuf, String> {
    let mut files = BTreeMap::new();
    files.insert(PathBuf::from("mod.rs"), emit_mod_rs(spec));
    for state in STATES {
        files.insert(
            PathBuf::from(format!("{}.rs", state.module())),
            emit_state_module(spec, packets, state),
        );
    }
    files
}

/// The two header comment lines (the `@generated` marker and the source pin)
/// prepended to every generated file.
fn file_header(spec: &Spec) -> String {
    format!(
        "{GENERATED_HEADER}\n\
         // source: minecraft-data {commit} (Minecraft {version}, protocol {protocol}, data version {data})\n",
        commit = spec.source_commit,
        version = MINECRAFT_VERSION,
        protocol = spec.protocol_version,
        data = spec.data_version,
    )
}

/// Renders the `generated/mod.rs` root: header, source pin, the protocol version
/// constant, and the per-state module declarations.
fn emit_mod_rs(spec: &Spec) -> String {
    let mut out = file_header(spec);
    let _ = write!(
        out,
        "\n//! Generated protocol definitions for Minecraft {version} (protocol {protocol}).\n\
         //!\n\
         //! Do not edit by hand: run `cargo xtask generate` to regenerate, and\n\
         //! `cargo xtask generate --check` to verify this tree is up to date.\n\
         \n\
         /// Protocol (network) version negotiated in the handshake for Minecraft {version}.\n\
         ///\n\
         /// Shared with 1.21.7; releases are disambiguated by the world data version,\n\
         /// not by this value.\n\
         pub const PROTOCOL_VERSION: i32 = {protocol};\n\n",
        version = MINECRAFT_VERSION,
        protocol = spec.protocol_version,
    );
    // rustfmt sorts these alphabetically; emit in state order for readability.
    for state in STATES {
        let _ = writeln!(out, "pub mod {};", state.module());
    }
    out
}

/// Renders one state module: its shared structs, packets, and dispatch enums.
fn emit_state_module(spec: &Spec, packets: &PacketSpec, state: State) -> String {
    let mut out = file_header(spec);
    let _ = write!(
        out,
        "\n//! Packets for the {module} state (Minecraft {version}, protocol {protocol}).\n\
         \n\
         use bytes::BytesMut;\n\
         \n\
         use ferrumc_codec::{{BoundedReader, BoundedString}};\n\
         \n\
         use crate::error::ProtoError;\n\
         use crate::wire;\n\
         use crate::{{Direction, State}};\n",
        module = state.module(),
        version = MINECRAFT_VERSION,
        protocol = spec.protocol_version,
    );

    for st in structs_for_state(packets, state) {
        out.push('\n');
        out.push_str(&render_struct(packets, &st.name, &st.fields, None));
    }

    for packet in packets.packets.iter().filter(|p| p.state == state) {
        out.push('\n');
        out.push_str(&render_struct(
            packets,
            &packet.name,
            &packet.fields,
            Some(packet),
        ));
    }

    for direction in [Direction::Serverbound, Direction::Clientbound] {
        let group: Vec<&PacketDef> = packets
            .packets
            .iter()
            .filter(|p| p.state == state && p.direction == direction)
            .collect();
        if group.is_empty() {
            continue;
        }
        out.push('\n');
        out.push_str(&render_dispatch(packets, state, direction, &group));
    }

    out
}

/// Renders a struct (shared payload or packet) with its constructor, getters,
/// `decode`, and `encode`. When `packet` is `Some`, a `PACKET_ID` constant is
/// emitted and `encode` writes the id before the body.
fn render_struct(
    spec: &PacketSpec,
    name: &str,
    fields: &[Field],
    packet: Option<&PacketDef>,
) -> String {
    let eq = fields_are_eq(spec, fields);
    let mut out = String::new();

    // Struct definition.
    if let Some(p) = packet {
        let _ = writeln!(
            out,
            "/// `{name}`: the {state} {dir} packet (wire id `{id:#04x}`).",
            state = p.state.module(),
            dir = direction_word(p.direction),
            id = p.id,
        );
    } else {
        let _ = writeln!(out, "/// `{name}`: a composite payload used on the wire.");
    }
    out.push_str(derive_attr(eq));
    out.push('\n');
    if fields.is_empty() {
        let _ = writeln!(out, "pub struct {name};");
    } else {
        let _ = writeln!(out, "pub struct {name} {{");
        for f in fields {
            let _ = writeln!(out, "    {}: {},", field_ident(&f.name), f.ty.rust_type());
        }
        out.push_str("}\n");
    }

    // Inherent impl.
    let _ = writeln!(out, "\nimpl {name} {{");

    if let Some(p) = packet {
        let _ = writeln!(out, "/// The wire packet id for `{name}`.");
        let _ = writeln!(out, "pub const PACKET_ID: i32 = {:#04x};", p.id);
        out.push('\n');
    }

    if !fields.is_empty() {
        out.push_str(&render_constructor(name, fields));
        out.push('\n');
        for f in fields {
            out.push_str(&render_getter(f));
            out.push('\n');
        }
    }

    out.push_str(&render_decode(name, fields));
    out.push('\n');
    out.push_str(&render_encode(fields, packet.is_some()));

    out.push_str("}\n");
    out
}

/// Renders the `new` constructor that takes the wire fields by value.
fn render_constructor(name: &str, fields: &[Field]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "/// Creates a new `{name}` from its wire fields.");
    // The constructor mirrors the packet's fields one-to-one; a wide wire packet
    // legitimately needs many parameters, so silence the heuristic here.
    if fields.len() > 7 {
        out.push_str(
            "#[allow(clippy::too_many_arguments, reason = \"mirrors the packet's wire fields\")]\n",
        );
    }
    out.push_str("pub fn new(");
    let params: Vec<String> = fields
        .iter()
        .map(|f| format!("{}: {}", field_ident(&f.name), f.ty.rust_type()))
        .collect();
    out.push_str(&params.join(", "));
    out.push_str(") -> Self {\n");
    out.push_str("Self {\n");
    for f in fields {
        let _ = writeln!(out, "{},", field_ident(&f.name));
    }
    out.push_str("}\n}\n");
    out
}

/// Renders a by-value getter for `Copy` fields and a by-reference getter
/// otherwise.
fn render_getter(f: &Field) -> String {
    let ident = field_ident(&f.name);
    let mut out = String::new();
    let _ = writeln!(out, "/// Returns the `{}` field.", f.name);
    match &f.ty {
        ty if ty.is_copy() => {
            let _ = writeln!(
                out,
                "pub fn {ident}(&self) -> {ret} {{ self.{ident} }}",
                ret = ty.rust_type()
            );
        }
        WireType::Optional(inner) => {
            let _ = writeln!(
                out,
                "pub fn {ident}(&self) -> Option<&{inner}> {{ self.{ident}.as_ref() }}",
                inner = inner.rust_type()
            );
        }
        WireType::PrefixedArray(inner) => {
            let _ = writeln!(
                out,
                "pub fn {ident}(&self) -> &[{inner}] {{ &self.{ident} }}",
                inner = inner.rust_type()
            );
        }
        ty => {
            let _ = writeln!(
                out,
                "pub fn {ident}(&self) -> &{ret} {{ &self.{ident} }}",
                ret = ty.rust_type()
            );
        }
    }
    out
}

/// Renders the body-`decode` (the packet id, if any, is consumed by the caller).
fn render_decode(name: &str, fields: &[Field]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "/// Decodes a `{name}` body from `reader` (any packet id is already consumed)."
    );
    if fields.is_empty() {
        out.push_str(
            "pub fn decode(_reader: &mut BoundedReader<'_>) -> Result<Self, ProtoError> {\n\
             Ok(Self)\n}\n",
        );
        return out;
    }
    out.push_str("pub fn decode(reader: &mut BoundedReader<'_>) -> Result<Self, ProtoError> {\n");
    for f in fields {
        let _ = writeln!(
            out,
            "let {} = {};",
            field_ident(&f.name),
            decode_expr(&f.ty)
        );
    }
    out.push_str("Ok(Self {\n");
    for f in fields {
        let _ = writeln!(out, "{},", field_ident(&f.name));
    }
    out.push_str("})\n}\n");
    out
}

/// Renders `encode`. When `is_packet`, the packet id is written first.
fn render_encode(fields: &[Field], is_packet: bool) -> String {
    let mut out = String::new();
    out.push_str("/// Encodes this value (packet id, when present, then fields) into `buf`.\n");
    let buf_used = is_packet || !fields.is_empty();
    let buf_param = if buf_used { "buf" } else { "_buf" };
    let _ = writeln!(
        out,
        "pub fn encode(&self, {buf_param}: &mut BytesMut) -> Result<(), ProtoError> {{"
    );
    if is_packet {
        out.push_str("ferrumc_codec::write_var_int(buf, Self::PACKET_ID);\n");
    }
    for f in fields {
        out.push_str(&encode_stmt(
            &f.ty,
            &format!("self.{}", field_ident(&f.name)),
            false,
        ));
        out.push('\n');
    }
    out.push_str("Ok(())\n}\n");
    out
}

/// Renders the per-(state, direction) dispatch enum and its `decode` / `encode`
/// / `packet_id` methods.
fn render_dispatch(
    spec: &PacketSpec,
    state: State,
    direction: Direction,
    group: &[&PacketDef],
) -> String {
    let enum_name = format!("{}{}Packet", direction.variant(), state.variant());
    let eq = group.iter().all(|p| fields_are_eq(spec, &p.fields));

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/// {dir} packets in the {state} state, dispatched by wire id.",
        dir = direction_word(direction),
        state = state.module(),
    );
    out.push_str(derive_attr(eq));
    out.push('\n');
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for p in group {
        let _ = writeln!(out, "/// The `{n}` packet.", n = p.name);
        let _ = writeln!(out, "{n}({n}),", n = p.name);
    }
    out.push_str("}\n\n");

    let _ = writeln!(out, "impl {enum_name} {{");

    // decode(id, reader)
    let _ = writeln!(
        out,
        "/// Decodes a {dir} {state} packet body selected by its wire `id`.",
        dir = direction_word(direction),
        state = state.module(),
    );
    out.push_str(
        "pub fn decode(id: i32, reader: &mut BoundedReader<'_>) -> Result<Self, ProtoError> {\n\
         match id {\n",
    );
    for p in group {
        let _ = writeln!(
            out,
            "{n}::PACKET_ID => Ok(Self::{n}({n}::decode(reader)?)),",
            n = p.name
        );
    }
    let _ = writeln!(
        out,
        "other => Err(ProtoError::UnknownPacketId {{ state: State::{s}, direction: Direction::{d}, id: other }}),",
        s = state.variant(),
        d = direction.variant(),
    );
    out.push_str("}\n}\n\n");

    // packet_id(&self)
    out.push_str("/// Returns the wire packet id of this packet.\n");
    out.push_str("pub fn packet_id(&self) -> i32 {\n match self {\n");
    for p in group {
        let _ = writeln!(out, "Self::{n}(_) => {n}::PACKET_ID,", n = p.name);
    }
    out.push_str("}\n}\n\n");

    // encode(&self, buf)
    out.push_str("/// Encodes this packet (id followed by its body) into `buf`.\n");
    out.push_str(
        "pub fn encode(&self, buf: &mut BytesMut) -> Result<(), ProtoError> {\n match self {\n",
    );
    for p in group {
        let _ = writeln!(out, "Self::{n}(packet) => packet.encode(buf),", n = p.name);
    }
    out.push_str("}\n}\n}\n");

    out
}

/// The decode expression for one wire type, reading from `reader`.
fn decode_expr(ty: &WireType) -> String {
    match ty {
        WireType::VarInt => "reader.read_var_int()?".to_owned(),
        WireType::VarLong => "reader.read_var_long()?".to_owned(),
        WireType::U16 => "reader.read_u16()?".to_owned(),
        WireType::I64 => "reader.read_i64()?".to_owned(),
        WireType::I8 => "reader.read_i8()?".to_owned(),
        WireType::U8 => "reader.read_u8()?".to_owned(),
        WireType::Bool => "wire::read_bool(reader)?".to_owned(),
        WireType::Uuid => "wire::read_uuid(reader)?".to_owned(),
        WireType::Str(max) => {
            format!("BoundedString::<{}>::read(reader)?", group_digits(*max))
        }
        WireType::Identifier => format!(
            "BoundedString::<{}>::read(reader)?",
            group_digits(crate::packets::IDENTIFIER_MAX)
        ),
        WireType::Nbt => nbt_decode_block(),
        WireType::Optional(inner) => {
            format!(
                "if wire::read_bool(reader)? {{ Some({}) }} else {{ None }}",
                decode_expr(inner)
            )
        }
        WireType::PrefixedArray(inner) => format!(
            "{{ let count = wire::read_prefixed_len(reader)?; \
             let mut items = Vec::with_capacity(count.min(reader.remaining())); \
             for _ in 0..count {{ items.push({}); }} items }}",
            decode_expr(inner)
        ),
        WireType::Struct(struct_name) => format!("{struct_name}::decode(reader)?"),
    }
}

/// The decode block for an embedded network-form NBT root. It parses exactly one
/// root, then rebinds `reader` to the bytes after it so later fields read on.
fn nbt_decode_block() -> String {
    "{ let available = reader.remaining(); \
     let bytes = reader.read_bytes(available)?; \
     let (tag, consumed) = \
     ferrumc_nbt::read_network_root_with_consumed(bytes, &ferrumc_nbt::NbtLimits::default())?; \
     *reader = BoundedReader::new(bytes.get(consumed..).unwrap_or_default()); \
     tag }"
        .to_owned()
}

/// One or more statements that encode a wire value at `place` into `buf`.
///
/// `is_ref` is `true` when `place` is already a reference to the value (the case
/// for elements bound inside `optional` / `prefixed_array` handling); it is
/// `false` for a `self.field` place.
fn encode_stmt(ty: &WireType, place: &str, is_ref: bool) -> String {
    let value = if is_ref {
        format!("*{place}")
    } else {
        place.to_owned()
    };
    match ty {
        WireType::VarInt => format!("ferrumc_codec::write_var_int(buf, {value});"),
        WireType::VarLong => format!("ferrumc_codec::write_var_long(buf, {value});"),
        WireType::U16 => format!("wire::write_u16(buf, {value});"),
        WireType::I64 => format!("wire::write_i64(buf, {value});"),
        WireType::I8 => format!("wire::write_i8(buf, {value});"),
        WireType::U8 => format!("wire::write_u8(buf, {value});"),
        WireType::Bool => format!("wire::write_bool(buf, {value});"),
        WireType::Uuid => format!("wire::write_uuid(buf, {value});"),
        WireType::Str(_) | WireType::Identifier => format!("{place}.write(buf);"),
        WireType::Struct(_) => format!("{place}.encode(buf)?;"),
        WireType::Nbt => {
            let arg = if is_ref {
                place.to_owned()
            } else {
                format!("&{place}")
            };
            format!(
                "{{ let nbt_bytes = \
                 ferrumc_nbt::write_network_root({arg}, &ferrumc_nbt::NbtLimits::default())?; \
                 wire::write_raw(buf, &nbt_bytes); }}"
            )
        }
        WireType::Optional(inner) => {
            let target = if is_ref {
                place.to_owned()
            } else {
                format!("&{place}")
            };
            format!(
                "match {target} {{ Some(inner) => {{ wire::write_bool(buf, true); {} }} \
                 None => {{ wire::write_bool(buf, false); }} }}",
                encode_stmt(inner, "inner", true)
            )
        }
        WireType::PrefixedArray(inner) => {
            let iter = if is_ref {
                place.to_owned()
            } else {
                format!("&{place}")
            };
            format!(
                "wire::write_prefixed_len(buf, {place}.len()); for elem in {iter} {{ {} }}",
                encode_stmt(inner, "elem", true)
            )
        }
    }
}

/// The set of structs (transitively) referenced by a state's packets, in the
/// spec's sorted order, so each state module is self-contained.
fn structs_for_state(spec: &PacketSpec, state: State) -> Vec<&StructDef> {
    let mut wanted = BTreeSet::new();
    for p in spec.packets.iter().filter(|p| p.state == state) {
        for f in &p.fields {
            collect_struct_refs(&f.ty, &mut wanted);
        }
    }
    loop {
        let snapshot: Vec<String> = wanted.iter().cloned().collect();
        let before = wanted.len();
        for n in snapshot {
            if let Some(sd) = spec.structs.iter().find(|s| s.name == n) {
                for f in &sd.fields {
                    collect_struct_refs(&f.ty, &mut wanted);
                }
            }
        }
        if wanted.len() == before {
            break;
        }
    }
    spec.structs
        .iter()
        .filter(|s| wanted.contains(&s.name))
        .collect()
}

/// Adds every struct name reachable from `ty` to `set`.
fn collect_struct_refs(ty: &WireType, set: &mut BTreeSet<String>) {
    match ty {
        WireType::Optional(inner) | WireType::PrefixedArray(inner) => {
            collect_struct_refs(inner, set);
        }
        WireType::Struct(name) => {
            set.insert(name.clone());
        }
        _ => {}
    }
}

/// Whether a set of fields can derive `Eq` (no NBT, which carries floats).
fn fields_are_eq(spec: &PacketSpec, fields: &[Field]) -> bool {
    fields.iter().all(|f| type_is_eq(spec, &f.ty))
}

/// Whether a single wire type's Rust mapping can derive `Eq`.
fn type_is_eq(spec: &PacketSpec, ty: &WireType) -> bool {
    match ty {
        WireType::Nbt => false,
        WireType::Optional(inner) | WireType::PrefixedArray(inner) => type_is_eq(spec, inner),
        WireType::Struct(name) => match spec.structs.iter().find(|s| s.name == *name) {
            Some(sd) => fields_are_eq(spec, &sd.fields),
            None => true,
        },
        _ => true,
    }
}

/// The derive attribute line, adding `Eq` only when the type supports it.
fn derive_attr(eq: bool) -> &'static str {
    if eq {
        "#[derive(Debug, Clone, PartialEq, Eq)]"
    } else {
        "#[derive(Debug, Clone, PartialEq)]"
    }
}

/// The human-readable direction word used in doc comments.
fn direction_word(direction: Direction) -> &'static str {
    match direction {
        Direction::Serverbound => "serverbound",
        Direction::Clientbound => "clientbound",
    }
}

/// Wraps a field name as a raw identifier when it collides with a Rust keyword,
/// so spec authors can use names like `type` without breaking generation.
fn field_ident(name: &str) -> String {
    const KEYWORDS: [&str; 6] = ["type", "match", "move", "ref", "self", "where"];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_owned()
    }
}

/// Normalizes a `.rs` source string into its canonical, byte-stable form.
///
/// Runs the real `rustfmt` (pinned via `rust-toolchain.toml`) over the input,
/// then forces LF line endings and exactly one trailing newline. Returns
/// [`GenError::Rustfmt`] if `rustfmt` cannot be spawned, exits non-zero, or
/// produces non-UTF-8 output.
pub(crate) fn normalize_rust(source: &str) -> Result<String, GenError> {
    let formatted = run_rustfmt(source)?;
    Ok(normalize_endings(&formatted))
}

/// Forces LF endings and a single trailing newline on already-formatted text.
pub(crate) fn normalize_endings(text: &str) -> String {
    let mut out: String = text.replace("\r\n", "\n").replace('\r', "\n");
    while out.ends_with('\n') {
        out.pop();
    }
    out.push('\n');
    out
}

/// Pipes `source` through `rustfmt` via stdin/stdout (no temp files).
fn run_rustfmt(source: &str) -> Result<String, GenError> {
    let program = std::env::var("RUSTFMT").unwrap_or_else(|_| "rustfmt".to_string());

    let mut child = Command::new(&program)
        .arg("--edition")
        .arg("2021")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|source| GenError::Rustfmt(format!("could not spawn `{program}`: {source}")))?;

    {
        let stdin = child
            .stdin
            .as_mut()
            .ok_or_else(|| GenError::Rustfmt("rustfmt stdin was not captured".to_string()))?;
        stdin
            .write_all(source.as_bytes())
            .map_err(|source| GenError::Rustfmt(format!("writing to rustfmt failed: {source}")))?;
    }

    let output = child
        .wait_with_output()
        .map_err(|source| GenError::Rustfmt(format!("waiting on rustfmt failed: {source}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(GenError::Rustfmt(format!(
            "rustfmt exited with {}: {}",
            output.status,
            stderr.trim()
        )));
    }

    String::from_utf8(output.stdout)
        .map_err(|_| GenError::Rustfmt("rustfmt produced non-UTF-8 output".to_string()))
}
