//! The set of chunks a shard owns in memory, governed by tickets.
//!
//! A [`LoadedChunkMap`] is the shard's exclusive owner of chunk data for one
//! world and dimension. A chunk becomes resident the moment it gets its first
//! [`ChunkTicket`] (via [`LoadedChunkMap::acquire`], which runs the
//! load-or-generate flow) and is unloaded the moment its last ticket is released
//! (via [`LoadedChunkMap::release`]). The map therefore maintains one
//! invariant at all times:
//!
//! > A chunk position is resident **iff** it holds at least one ticket.
//!
//! Mutations to a resident chunk mark it dirty (the chunk tracks this itself);
//! [`LoadedChunkMap::take_dirty`] hands those dirty chunks off as save records.
//! This module collects dirty chunks but never persists them — choosing *when*
//! to flush is the caller's policy, deliberately out of scope here.

use std::collections::btree_map::Entry;
use std::collections::BTreeMap;

use ferrumc_core::{DimensionId, WorldId};
use ferrumc_math::ChunkPos;
use ferrumc_storage::{ChunkKey, ChunkRecord, SchemaVersion, WorldStore};
use ferrumc_world::{Chunk, FlatWorldGenerator};

use crate::error::{SimError, SimResult};
use crate::spawn::SpawnChunkTickets;
use crate::ticket::{ChunkTicket, TicketLevel};

/// The schema version the simulation stamps on chunks it hands off to be saved.
///
/// Chunks generated by the simulation (and any resident chunk re-saved after a
/// mutation) are written under this version so a future storage backend can
/// detect and migrate older data. It is the simulation's notion of "current";
/// storage preserves it verbatim.
pub const CHUNK_SCHEMA_VERSION: SchemaVersion = SchemaVersion::new(1);

/// How a chunk entered memory during the load-or-generate flow.
///
/// Returned by [`load_or_generate`] and carried by
/// [`ChunkAcquired::NewlyResident`]. The enum is `#[non_exhaustive]`; prefer the
/// [`is_loaded`](Self::is_loaded) / [`is_generated`](Self::is_generated)
/// predicates over matching it directly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum ChunkProvenance {
    /// The chunk was read back from the [`WorldStore`].
    Loaded,

    /// The store had no chunk at the key, so it was freshly generated.
    Generated,
}

impl ChunkProvenance {
    /// Returns `true` if the chunk was read from storage.
    #[must_use]
    pub fn is_loaded(self) -> bool {
        matches!(self, ChunkProvenance::Loaded)
    }

    /// Returns `true` if the chunk was freshly generated on a storage miss.
    #[must_use]
    pub fn is_generated(self) -> bool {
        matches!(self, ChunkProvenance::Generated)
    }
}

/// The outcome of [`LoadedChunkMap::acquire`].
///
/// The enum is `#[non_exhaustive]`; prefer the predicate methods over matching
/// it directly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum ChunkAcquired {
    /// The chunk was not resident, so the load-or-generate flow brought it in.
    /// Carries how it was obtained.
    NewlyResident(ChunkProvenance),

    /// The chunk was already resident; only the new ticket was recorded.
    AlreadyResident,
}

impl ChunkAcquired {
    /// Returns the provenance if the chunk was newly brought into memory, or
    /// `None` if it was already resident.
    #[must_use]
    pub fn provenance(self) -> Option<ChunkProvenance> {
        match self {
            ChunkAcquired::NewlyResident(p) => Some(p),
            ChunkAcquired::AlreadyResident => None,
        }
    }

    /// Returns `true` if the load-or-generate flow ran for this acquire.
    #[must_use]
    pub fn is_newly_resident(self) -> bool {
        matches!(self, ChunkAcquired::NewlyResident(_))
    }

    /// Returns `true` if the chunk was already resident and only a ticket was
    /// added.
    #[must_use]
    pub fn is_already_resident(self) -> bool {
        matches!(self, ChunkAcquired::AlreadyResident)
    }
}

/// The outcome of [`LoadedChunkMap::release`].
///
/// The enum is `#[non_exhaustive]`; prefer the predicate and accessor methods
/// over matching it directly.
#[derive(Debug)]
#[non_exhaustive]
pub enum TicketRelease {
    /// The ticket was removed but the chunk retains other tickets and stays
    /// resident.
    StillLoaded,

    /// The last ticket was removed and the chunk was unloaded. If it had
    /// unsaved changes, `dirty` carries the record the caller must persist
    /// before the chunk is gone for good.
    Unloaded {
        /// The save record for the unloaded chunk, present only if it was dirty.
        ///
        /// Boxed because a [`ChunkRecord`] is large (a whole chunk column) while
        /// the other outcomes carry nothing — keeping the record behind a
        /// pointer keeps every [`TicketRelease`] value small.
        dirty: Option<Box<(ChunkKey, ChunkRecord)>>,
    },

    /// No matching ticket existed at the position; nothing changed.
    NotPresent,
}

impl TicketRelease {
    /// Returns `true` if the chunk is still resident after the release.
    #[must_use]
    pub fn is_still_loaded(&self) -> bool {
        matches!(self, TicketRelease::StillLoaded)
    }

    /// Returns `true` if the release unloaded the chunk.
    #[must_use]
    pub fn is_unloaded(&self) -> bool {
        matches!(self, TicketRelease::Unloaded { .. })
    }

    /// Returns `true` if no matching ticket was present.
    #[must_use]
    pub fn is_not_present(&self) -> bool {
        matches!(self, TicketRelease::NotPresent)
    }

    /// Consumes the outcome, returning the save record for an unloaded dirty
    /// chunk, or `None` in every other case.
    #[must_use]
    pub fn into_dirty(self) -> Option<(ChunkKey, ChunkRecord)> {
        match self {
            TicketRelease::Unloaded { dirty } => dirty.map(|boxed| *boxed),
            _ => None,
        }
    }
}

/// One resident chunk: its data plus the multiset of tickets keeping it loaded.
#[derive(Debug, Clone)]
struct ResidentChunk {
    chunk: Chunk,
    /// Each distinct ticket maps to the number of holders. Every count is `>= 1`;
    /// an entry dropping to zero is removed, and an empty map means the chunk
    /// should be unloaded.
    tickets: BTreeMap<ChunkTicket, usize>,
}

/// Runs the load-or-generate flow for a single chunk.
///
/// Tries [`WorldStore::load_chunk`] for `key`; on a hit it returns the stored
/// chunk, and on a miss it generates a fresh chunk for `key`'s position with
/// `generator`. The returned [`ChunkProvenance`] records which path was taken.
///
/// A storage failure is surfaced as [`SimError::ChunkLoad`]; a *missing* chunk
/// is not a failure (it is the generate path).
pub async fn load_or_generate(
    store: &dyn WorldStore,
    generator: &FlatWorldGenerator,
    key: ChunkKey,
) -> SimResult<(Chunk, ChunkProvenance)> {
    let pos = key.pos();
    let stored = store
        .load_chunk(key)
        .await
        .map_err(|source| SimError::ChunkLoad { pos, source })?;
    match stored {
        Some(record) => Ok((record.into_chunk(), ChunkProvenance::Loaded)),
        None => Ok((generator.generate(pos), ChunkProvenance::Generated)),
    }
}

/// The chunks a shard owns in memory for one world and dimension.
///
/// Construct one with [`LoadedChunkMap::new`], bring chunks in with
/// [`acquire`](Self::acquire), release them with [`release`](Self::release), and
/// drain pending saves with [`take_dirty`](Self::take_dirty). The map owns chunk
/// *data* but never a database handle: every storage call is made through a
/// borrowed [`WorldStore`] passed per acquire.
///
/// # Determinism
///
/// Residency is keyed by [`ChunkPos`] in an ordered [`BTreeMap`], and tickets in
/// an ordered map keyed by [`ChunkTicket`], so iteration order
/// ([`loaded_positions`](Self::loaded_positions), [`take_dirty`](Self::take_dirty))
/// is fully determined by the set of resident chunks — no hashing randomness
/// leaks in. Given the same store contents and the same acquire/release/mutate
/// sequence, the map reaches an identical state and produces identical dirty
/// batches.
#[derive(Debug, Clone)]
pub struct LoadedChunkMap {
    world: WorldId,
    dimension: DimensionId,
    schema_version: SchemaVersion,
    resident: BTreeMap<ChunkPos, ResidentChunk>,
}

impl LoadedChunkMap {
    /// Creates an empty map for `world` / `dimension`, saving chunks under
    /// [`CHUNK_SCHEMA_VERSION`].
    #[must_use]
    pub fn new(world: WorldId, dimension: DimensionId) -> Self {
        Self::with_schema_version(world, dimension, CHUNK_SCHEMA_VERSION)
    }

    /// Creates an empty map for `world` / `dimension` that saves chunks under an
    /// explicit `schema_version`.
    #[must_use]
    pub fn with_schema_version(
        world: WorldId,
        dimension: DimensionId,
        schema_version: SchemaVersion,
    ) -> Self {
        Self {
            world,
            dimension,
            schema_version,
            resident: BTreeMap::new(),
        }
    }

    /// Returns the world these chunks belong to.
    #[must_use]
    pub const fn world(&self) -> WorldId {
        self.world
    }

    /// Returns the dimension these chunks belong to.
    #[must_use]
    pub const fn dimension(&self) -> DimensionId {
        self.dimension
    }

    /// Returns the schema version chunks are saved under.
    #[must_use]
    pub const fn schema_version(&self) -> SchemaVersion {
        self.schema_version
    }

    /// Returns the number of resident chunks.
    #[must_use]
    pub fn loaded_count(&self) -> usize {
        self.resident.len()
    }

    /// Returns `true` if the chunk at `pos` is resident.
    #[must_use]
    pub fn is_loaded(&self, pos: ChunkPos) -> bool {
        self.resident.contains_key(&pos)
    }

    /// Returns the resident chunk positions in ascending order.
    pub fn loaded_positions(&self) -> impl Iterator<Item = ChunkPos> + '_ {
        self.resident.keys().copied()
    }

    /// Returns a shared reference to the resident chunk at `pos`, or `None` if it
    /// is not loaded.
    #[must_use]
    pub fn get(&self, pos: ChunkPos) -> Option<&Chunk> {
        self.resident.get(&pos).map(|r| &r.chunk)
    }

    /// Returns a mutable reference to the resident chunk at `pos`, or `None` if
    /// it is not loaded.
    ///
    /// Mutating through the returned reference (for example
    /// [`Chunk::set_block`](ferrumc_world::Chunk::set_block)) marks the affected
    /// sections dirty, so the chunk is included in the next
    /// [`take_dirty`](Self::take_dirty).
    #[must_use]
    pub fn get_mut(&mut self, pos: ChunkPos) -> Option<&mut Chunk> {
        self.resident.get_mut(&pos).map(|r| &mut r.chunk)
    }

    /// Returns the total number of tickets currently held on `pos` (counting
    /// duplicate holders), or `0` if the chunk is not resident.
    #[must_use]
    pub fn ticket_count(&self, pos: ChunkPos) -> usize {
        self.resident
            .get(&pos)
            .map_or(0, |r| r.tickets.values().sum())
    }

    /// Returns the chunk's *effective* (strongest, i.e. lowest) ticket level, or
    /// `None` if it is not resident.
    #[must_use]
    pub fn effective_level(&self, pos: ChunkPos) -> Option<TicketLevel> {
        self.resident
            .get(&pos)
            .and_then(|r| r.tickets.keys().map(|t| t.level()).min())
    }

    /// Builds the storage key for a chunk position in this map's world and
    /// dimension.
    fn chunk_key(&self, pos: ChunkPos) -> ChunkKey {
        ChunkKey::new(self.world, self.dimension, pos)
    }

    /// Ensures the chunk at `pos` is resident and records `ticket` on it.
    ///
    /// If the chunk is already resident, the ticket is simply added and
    /// [`ChunkAcquired::AlreadyResident`] is returned. Otherwise the
    /// load-or-generate flow (see [`load_or_generate`]) brings it into memory
    /// with `ticket` as its first ticket, and
    /// [`ChunkAcquired::NewlyResident`] reports how it was obtained.
    ///
    /// Returns [`SimError::ChunkLoad`] if the store read fails; on failure the
    /// map is left unchanged.
    pub async fn acquire(
        &mut self,
        store: &dyn WorldStore,
        generator: &FlatWorldGenerator,
        pos: ChunkPos,
        ticket: ChunkTicket,
    ) -> SimResult<ChunkAcquired> {
        if let Some(resident) = self.resident.get_mut(&pos) {
            *resident.tickets.entry(ticket).or_insert(0) += 1;
            return Ok(ChunkAcquired::AlreadyResident);
        }

        // Not resident: run the flow before mutating the map so a load failure
        // leaves residency untouched.
        let key = self.chunk_key(pos);
        let (chunk, provenance) = load_or_generate(store, generator, key).await?;
        let mut tickets = BTreeMap::new();
        tickets.insert(ticket, 1usize);
        self.resident.insert(pos, ResidentChunk { chunk, tickets });
        Ok(ChunkAcquired::NewlyResident(provenance))
    }

    /// Acquires every chunk in `spawn` with its spawn ticket, returning the
    /// number that were newly brought into memory.
    ///
    /// Chunks already resident (for any reason) still receive a spawn ticket but
    /// are not counted as newly resident. Returns [`SimError::ChunkLoad`] if any
    /// underlying load fails, after which the chunks acquired so far remain
    /// resident.
    pub async fn acquire_spawn(
        &mut self,
        store: &dyn WorldStore,
        generator: &FlatWorldGenerator,
        spawn: &SpawnChunkTickets,
    ) -> SimResult<usize> {
        let ticket = spawn.ticket();
        let mut newly_resident = 0;
        for pos in spawn.positions() {
            if self
                .acquire(store, generator, pos, ticket)
                .await?
                .is_newly_resident()
            {
                newly_resident += 1;
            }
        }
        Ok(newly_resident)
    }

    /// Releases one `ticket` from the chunk at `pos`.
    ///
    /// Decrements that ticket's holder count. If it was the chunk's last ticket
    /// the chunk is unloaded; a dirty chunk's save record is returned in
    /// [`TicketRelease::Unloaded`] so the caller can persist it before it is
    /// dropped. Releasing a ticket that is not held (or a chunk that is not
    /// resident) is a no-op reported as [`TicketRelease::NotPresent`].
    pub fn release(&mut self, pos: ChunkPos, ticket: ChunkTicket) -> TicketRelease {
        let Some(resident) = self.resident.get_mut(&pos) else {
            return TicketRelease::NotPresent;
        };
        let Entry::Occupied(mut entry) = resident.tickets.entry(ticket) else {
            return TicketRelease::NotPresent;
        };
        let count = entry.get_mut();
        *count -= 1;
        if *count == 0 {
            entry.remove();
        }
        if !resident.tickets.is_empty() {
            return TicketRelease::StillLoaded;
        }

        // Last ticket gone: unload, surfacing the save record if it was dirty.
        let key = self.chunk_key(pos);
        match self.resident.remove(&pos) {
            Some(mut resident) => {
                let dirty = if resident.chunk.dirty_sections().any() {
                    resident.chunk.clear_dirty();
                    Some(Box::new((
                        key,
                        ChunkRecord::new(self.schema_version, resident.chunk),
                    )))
                } else {
                    None
                };
                TicketRelease::Unloaded { dirty }
            }
            // `pos` was present at the start of the method and only this `&mut`
            // path could have removed it, so this arm is unreachable; report it
            // as a no-op rather than panicking.
            None => TicketRelease::NotPresent,
        }
    }

    /// Collects every resident chunk with unsaved changes as a save batch and
    /// marks those chunks clean.
    ///
    /// Each returned `(ChunkKey, ChunkRecord)` is a snapshot ready to hand to
    /// [`WorldStore::save_chunks`]. The chunks' dirty flags are cleared here on
    /// the assumption the batch will be persisted; this method does not perform
    /// the save and intentionally implements no flush *policy* (when to call it,
    /// and what to do if the save later fails, are the caller's concern). The
    /// batch is ordered by [`ChunkPos`] for determinism.
    #[must_use]
    pub fn take_dirty(&mut self) -> Vec<(ChunkKey, ChunkRecord)> {
        let world = self.world;
        let dimension = self.dimension;
        let schema = self.schema_version;
        let mut batch = Vec::new();
        for (&pos, resident) in &mut self.resident {
            if resident.chunk.dirty_sections().any() {
                resident.chunk.clear_dirty();
                batch.push((
                    ChunkKey::new(world, dimension, pos),
                    ChunkRecord::new(schema, resident.chunk.clone()),
                ));
            }
        }
        batch
    }
}

#[cfg(test)]
mod tests {
    use ferrumc_core::{DimensionId, WorldId};
    use ferrumc_math::BlockPos;
    use ferrumc_storage::{ChunkKey, ChunkRecord, InMemoryStore, SchemaVersion, WorldStore};
    use ferrumc_world::{BlockStateId, Chunk};

    use super::*;
    use crate::ticket::{ChunkTicket, TicketReason};

    fn world() -> WorldId {
        WorldId::new(0)
    }

    fn dimension() -> DimensionId {
        DimensionId::new(0)
    }

    fn map() -> LoadedChunkMap {
        LoadedChunkMap::new(world(), dimension())
    }

    fn gen() -> FlatWorldGenerator {
        FlatWorldGenerator::new()
    }

    fn spawn_ticket() -> ChunkTicket {
        ChunkTicket::of(TicketReason::Spawn)
    }

    /// A clean (already-persisted) chunk carrying a single marker block, used to
    /// prove a load returns stored data rather than freshly generated terrain.
    fn marker_chunk(pos: ChunkPos, marker: BlockPos, state: BlockStateId) -> Chunk {
        let mut chunk = Chunk::new(pos);
        chunk.set_block(marker, state).expect("marker in chunk");
        chunk.clear_dirty();
        chunk
    }

    #[tokio::test]
    async fn acquire_miss_generates_hit_loads() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);

        // Empty store -> generate.
        let mut m = map();
        let outcome = m
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        assert_eq!(outcome.provenance(), Some(ChunkProvenance::Generated));
        // Generated flat terrain has a grass surface at y = 63.
        let surface = m
            .get(pos)
            .and_then(|c| c.get_block(BlockPos::new(0, 63, 0)))
            .expect("surface block");
        assert_ne!(surface, BlockStateId::AIR);

        // Pre-populate a *different* chunk and load it from a fresh map.
        let marker = BlockPos::new(1, 64, 1);
        let stored = marker_chunk(pos, marker, BlockStateId::new(7));
        let key = ChunkKey::new(world(), dimension(), pos);
        store
            .save_chunk(key, ChunkRecord::new(SchemaVersion::new(9), stored))
            .await
            .expect("save");

        let mut m2 = map();
        let outcome = m2
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        assert_eq!(outcome.provenance(), Some(ChunkProvenance::Loaded));
        // The loaded chunk is the stored one: marker present, no generated grass.
        let loaded = m2.get(pos).expect("resident");
        assert_eq!(loaded.get_block(marker), Some(BlockStateId::new(7)));
        assert_eq!(
            loaded.get_block(BlockPos::new(0, 63, 0)),
            Some(BlockStateId::AIR),
            "loaded chunk must not be regenerated"
        );
    }

    #[tokio::test]
    async fn second_acquire_is_already_resident() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(2, -1);
        let mut m = map();

        assert!(m
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("first")
            .is_newly_resident());
        let second = m
            .acquire(
                &store,
                &generator,
                pos,
                ChunkTicket::of(TicketReason::Player),
            )
            .await
            .expect("second");
        assert!(second.is_already_resident());
        assert_eq!(m.loaded_count(), 1);
        assert_eq!(m.ticket_count(pos), 2);
        // Effective level is the stronger (lower) of the two tickets.
        assert_eq!(m.effective_level(pos), Some(TicketLevel::ENTITY_TICKING));
    }

    #[tokio::test]
    async fn tickets_govern_the_loaded_set() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);
        let mut m = map();
        let ticket = spawn_ticket();

        assert!(!m.is_loaded(pos));
        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire");
        // Add a duplicate holder of the same ticket.
        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire dup");
        assert!(m.is_loaded(pos));
        assert_eq!(m.ticket_count(pos), 2);

        // First release: one duplicate holder remains, chunk stays loaded.
        assert!(m.release(pos, ticket).is_still_loaded());
        assert!(m.is_loaded(pos));

        // Second release: last ticket gone, chunk unloads.
        let release = m.release(pos, ticket);
        assert!(release.is_unloaded());
        assert!(!m.is_loaded(pos));
        assert_eq!(m.loaded_count(), 0);
    }

    #[tokio::test]
    async fn release_unknown_ticket_or_chunk_is_noop() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(5, 5);
        let mut m = map();

        // No chunk at all.
        assert!(m.release(pos, spawn_ticket()).is_not_present());

        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // A ticket the chunk does not hold.
        assert!(m
            .release(pos, ChunkTicket::of(TicketReason::Forced))
            .is_not_present());
        assert!(m.is_loaded(pos), "no-op release keeps the chunk loaded");
    }

    #[tokio::test]
    async fn dirty_chunks_collected_on_mutation() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);

        // Start from a clean, previously-saved chunk so dirtiness comes purely
        // from our mutation.
        let key = ChunkKey::new(world(), dimension(), pos);
        store
            .save_chunk(
                key,
                ChunkRecord::new(
                    SchemaVersion::new(1),
                    marker_chunk(pos, BlockPos::new(0, 0, 0), BlockStateId::new(1)),
                ),
            )
            .await
            .expect("save");

        let mut m = map();
        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // Freshly loaded clean chunk: nothing dirty.
        assert!(m.take_dirty().is_empty());

        // Mutate it.
        m.get_mut(pos)
            .expect("resident")
            .set_block(BlockPos::new(2, 70, 2), BlockStateId::new(5))
            .expect("in range");

        let dirty = m.take_dirty();
        assert_eq!(dirty.len(), 1);
        assert_eq!(dirty[0].0, key);
        // Draining clears dirtiness: a second take yields nothing.
        assert!(m.take_dirty().is_empty());
    }

    #[tokio::test]
    async fn generated_chunk_is_dirty_for_initial_save() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(3, 4);
        let mut m = map();

        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // A freshly generated chunk has filled sections and so is dirty: it must
        // be handed off for its first save.
        let dirty = m.take_dirty();
        assert_eq!(dirty.len(), 1);
        assert_eq!(dirty[0].0, ChunkKey::new(world(), dimension(), pos));
    }

    #[tokio::test]
    async fn unloading_dirty_chunk_surfaces_save_record() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(1, 1);
        let mut m = map();
        let ticket = spawn_ticket();

        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire");
        // Generated chunk is dirty; releasing the last ticket must surface its
        // save record so it is not lost on unload.
        let record = m.release(pos, ticket).into_dirty();
        assert!(record.is_some());
        assert!(!m.is_loaded(pos));
    }

    #[tokio::test]
    async fn acquire_spawn_loads_the_whole_set() {
        let store = InMemoryStore::new();
        let generator = gen();
        let spawn = SpawnChunkTickets::new(ChunkPos::new(0, 0), 1);
        let mut m = map();

        let newly = m
            .acquire_spawn(&store, &generator, &spawn)
            .await
            .expect("acquire_spawn");
        assert_eq!(newly, 9);
        assert_eq!(m.loaded_count(), 9);
        for pos in spawn.positions() {
            assert!(m.is_loaded(pos));
            assert_eq!(m.effective_level(pos), Some(TicketLevel::TICKING));
        }
    }

    #[tokio::test]
    async fn free_load_or_generate_reports_provenance() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(8, 8);
        let key = ChunkKey::new(world(), dimension(), pos);

        // Miss -> generate the requested position.
        let (chunk, prov) = load_or_generate(&store, &generator, key)
            .await
            .expect("generate path");
        assert!(prov.is_generated());
        assert_eq!(chunk.pos(), pos);

        // Hit -> return the stored chunk.
        store
            .save_chunk(key, ChunkRecord::new(SchemaVersion::new(1), chunk))
            .await
            .expect("save");
        let (_, prov) = load_or_generate(&store, &generator, key)
            .await
            .expect("load path");
        assert!(prov.is_loaded());
    }

    #[tokio::test]
    async fn loaded_positions_are_sorted_and_deterministic() {
        let store = InMemoryStore::new();
        let generator = gen();
        let mut m = map();
        for pos in [
            ChunkPos::new(2, 0),
            ChunkPos::new(-1, 3),
            ChunkPos::new(0, 0),
        ] {
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire");
        }
        let order: Vec<ChunkPos> = m.loaded_positions().collect();
        assert_eq!(
            order,
            vec![
                ChunkPos::new(-1, 3),
                ChunkPos::new(0, 0),
                ChunkPos::new(2, 0),
            ]
        );
    }
}
