//! The set of chunks a shard owns in memory, governed by tickets.
//!
//! A [`LoadedChunkMap`] is the shard's exclusive owner of chunk data for one
//! world and dimension. A chunk becomes resident the moment it gets its first
//! [`ChunkTicket`] (via [`LoadedChunkMap::acquire`], which runs the
//! load-or-generate flow) and is unloaded the moment its last ticket is released
//! (via [`LoadedChunkMap::release`]). The map therefore maintains one
//! invariant at all times:
//!
//! > A chunk position is resident **iff** it holds at least one ticket.
//!
//! Mutations to a resident chunk mark it dirty (the chunk tracks this itself).
//! There are two handoffs: [`LoadedChunkMap::take_dirty`] emits a full
//! [`ChunkRecord`] for every network-dirty chunk (including freshly generated
//! ones), while [`LoadedChunkMap::take_persist_dirty`] emits a
//! [`ChunkOverlayRecord`] only for chunks a *gameplay* edit marked persist-dirty
//! — so untouched generated terrain produces zero overlay records. This module
//! collects but never persists; choosing *when* to flush is the caller's policy,
//! deliberately out of scope here. The crate-internal multi-shard scheduler uses
//! a bounded canonical-order variant with a deterministic continuation cursor,
//! leaving overflow dirty without allowing low-key re-dirties to starve it.

use std::collections::btree_map::Entry;
use std::collections::BTreeMap;
use std::num::NonZeroUsize;
use std::ops::Bound::{Excluded, Unbounded};

use ferrumc_core::{DimensionId, WorldId};
use ferrumc_math::ChunkPos;
use ferrumc_storage::{
    ChunkKey, ChunkOverlayRecord, ChunkRecord, SchemaVersion, StorageError, WorldStore,
};
use ferrumc_world::{Chunk, FlatWorldGenerator};

use crate::error::{SimError, SimResult};
use crate::spawn::SpawnChunkTickets;
#[cfg(test)]
use crate::ticket::TicketReason;
use crate::ticket::{ChunkTicket, TicketLevel};

/// The schema version the simulation stamps on chunks it hands off to be saved.
///
/// Chunks generated by the simulation (and any resident chunk re-saved after a
/// mutation) are written under this version so a storage boundary can detect
/// and refuse incompatible data. It is the simulation's notion of "current";
/// storage preserves it verbatim.
pub const CHUNK_SCHEMA_VERSION: SchemaVersion = SchemaVersion::new(1);

/// The schema version stamped on chunk *overlay* records.
///
/// Distinct from [`CHUNK_SCHEMA_VERSION`] (full-chunk snapshots, v1): an overlay
/// carries only the player-modified sections plus a section mask, capture tick,
/// and the chunk's block entities, a different on-disk shape, so it is versioned
/// separately. The current schema carries the complete block-entity section
/// (sign text + chest contents). The simulation refuses every other overlay
/// schema rather than interpreting pre-alpha data under this layout. The
/// simulation owns this application schema; storage preserves it as opaque
/// payload metadata.
pub const OVERLAY_SCHEMA_VERSION: SchemaVersion = SchemaVersion::new(3);

/// How a chunk entered memory during the load-or-generate flow.
///
/// Returned by [`load_or_generate`] and carried by
/// [`ChunkAcquired::NewlyResident`]. The enum is `#[non_exhaustive]`; prefer the
/// [`is_loaded`](Self::is_loaded) / [`is_generated`](Self::is_generated)
/// predicates over matching it directly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum ChunkProvenance {
    /// The chunk was read back from the [`WorldStore`].
    Loaded,

    /// The store had no chunk at the key, so it was freshly generated.
    Generated,
}

impl ChunkProvenance {
    /// Returns `true` if the chunk was read from storage.
    #[must_use]
    pub fn is_loaded(self) -> bool {
        matches!(self, ChunkProvenance::Loaded)
    }

    /// Returns `true` if the chunk was freshly generated on a storage miss.
    #[must_use]
    pub fn is_generated(self) -> bool {
        matches!(self, ChunkProvenance::Generated)
    }
}

/// The outcome of [`LoadedChunkMap::acquire`].
///
/// The enum is `#[non_exhaustive]`; prefer the predicate methods over matching
/// it directly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum ChunkAcquired {
    /// The chunk was not resident, so the load-or-generate flow brought it in.
    /// Carries how it was obtained.
    NewlyResident(ChunkProvenance),

    /// The chunk was already resident; only the new ticket was recorded.
    AlreadyResident,
}

impl ChunkAcquired {
    /// Returns the provenance if the chunk was newly brought into memory, or
    /// `None` if it was already resident.
    #[must_use]
    pub fn provenance(self) -> Option<ChunkProvenance> {
        match self {
            ChunkAcquired::NewlyResident(p) => Some(p),
            ChunkAcquired::AlreadyResident => None,
        }
    }

    /// Returns `true` if the load-or-generate flow ran for this acquire.
    #[must_use]
    pub fn is_newly_resident(self) -> bool {
        matches!(self, ChunkAcquired::NewlyResident(_))
    }

    /// Returns `true` if the chunk was already resident and only a ticket was
    /// added.
    #[must_use]
    pub fn is_already_resident(self) -> bool {
        matches!(self, ChunkAcquired::AlreadyResident)
    }
}

/// The outcome of [`LoadedChunkMap::release`].
///
/// The enum is `#[non_exhaustive]`; prefer the predicate and accessor methods
/// over matching it directly.
#[derive(Debug)]
#[non_exhaustive]
pub enum TicketRelease {
    /// The ticket was removed but the chunk retains other tickets and stays
    /// resident.
    StillLoaded,

    /// The last ticket was removed and the chunk was unloaded.
    ///
    /// Persistence is **not** surfaced here: a chunk's player edits are captured
    /// into overlay records by [`take_persist_dirty`](LoadedChunkMap::take_persist_dirty)
    /// at the tick boundary (and again, by the caller, immediately before an
    /// unload), so an unloaded chunk has nothing left to save. A generated-only
    /// chunk has no persist-dirty sections and therefore costs no storage on
    /// unload, which is the whole point of the persist-dirty signal.
    Unloaded,

    /// No matching ticket existed at the position; nothing changed.
    NotPresent,
}

impl TicketRelease {
    /// Returns `true` if the chunk is still resident after the release.
    #[must_use]
    pub fn is_still_loaded(&self) -> bool {
        matches!(self, TicketRelease::StillLoaded)
    }

    /// Returns `true` if the release unloaded the chunk.
    #[must_use]
    pub fn is_unloaded(&self) -> bool {
        matches!(self, TicketRelease::Unloaded)
    }

    /// Returns `true` if no matching ticket was present.
    #[must_use]
    pub fn is_not_present(&self) -> bool {
        matches!(self, TicketRelease::NotPresent)
    }
}

/// One resident chunk: its data plus the multiset of tickets keeping it loaded.
#[derive(Debug, Clone)]
struct ResidentChunk {
    chunk: Chunk,
    /// Each distinct ticket maps to the number of holders. Every count is `>= 1`;
    /// an entry dropping to zero is removed, and an empty map means the chunk
    /// should be unloaded.
    tickets: BTreeMap<ChunkTicket, usize>,
}

/// Runs the load-or-generate flow for a single chunk.
///
/// Resolution order, all surfacing a storage failure as [`SimError::ChunkLoad`]:
/// 1. **Base**: use the complete record from [`WorldStore::load_chunk`] when one
///    exists; otherwise generate a fresh flat chunk for `key`'s position.
/// 2. **Overlay**: when [`WorldStore::load_chunk_overlay`] returns a record, apply
///    only its player-modified sections over that base with
///    [`ChunkOverlayRecord::apply_to_chunk`]. An imported full record therefore
///    remains authoritative everywhere the overlay has no data.
///
/// An overlay whose schema differs from [`OVERLAY_SCHEMA_VERSION`] is refused
/// with [`StorageError::IncompatiblePreAlphaData`] before any of its data is
/// applied.
///
/// The returned [`ChunkProvenance`] is [`Loaded`](ChunkProvenance::Loaded) when
/// either record exists and [`Generated`](ChunkProvenance::Generated) only when
/// both reads miss. A loaded chunk is returned clean: both the network and
/// per-flush persist-dirty masks are cleared, since the composition is already
/// persisted. When an overlay exists, the chunk's *cumulative* persist-edited set
/// is additionally reseeded from its sections, so a later edit to a different
/// section re-captures the whole overlay rather than overwriting earlier edits;
/// the per-flush gate stays clear, so the reseed does not itself trigger a flush.
pub async fn load_or_generate(
    store: &dyn WorldStore,
    generator: &FlatWorldGenerator,
    key: ChunkKey,
) -> SimResult<(Chunk, ChunkProvenance)> {
    let pos = key.pos();

    // The durable full record is the base when present. In particular, this is
    // the shape produced by Anvil import and must not be bypassed merely because
    // the chunk also has a later gameplay overlay.
    let stored = store
        .load_chunk(key)
        .await
        .map_err(|source| SimError::ChunkLoad { pos, source })?;
    let has_stored_base = stored.is_some();
    let mut chunk = stored.map_or_else(|| generator.generate(pos), ChunkRecord::into_chunk);

    // Apply only the overlay's carried sections and block entities over the
    // selected base. An empty overlay is therefore a no-op, not a reason to
    // replace an imported base with generated terrain.
    let overlay = store
        .load_chunk_overlay(key)
        .await
        .map_err(|source| SimError::ChunkLoad { pos, source })?;
    if let Some(overlay) = overlay {
        if overlay.schema_version() != OVERLAY_SCHEMA_VERSION {
            return Err(SimError::ChunkLoad {
                pos,
                source: StorageError::IncompatiblePreAlphaData.into(),
            });
        }

        // Every accepted nonempty overlay carries the chunk's complete
        // block-entity map. Clear the imported base map before applying that
        // snapshot so a removed sign/chest cannot resurrect on reload. A truly
        // empty current overlay remains the explicit no-op required by the load
        // contract.
        let replaces_block_entities = has_stored_base && overlay.section_count() != 0;
        if replaces_block_entities {
            let base_block_entities: Vec<_> = chunk
                .block_entities()
                .map(|(block_pos, _entity)| block_pos)
                .collect();
            for block_pos in base_block_entities {
                chunk.remove_block_entity(block_pos);
            }
        }
        overlay
            .apply_to_chunk(&mut chunk)
            .map_err(|source| SimError::ChunkLoad {
                pos,
                source: source.into(),
            })?;
        // Reseed the cumulative persist-edited set from the sections the overlay
        // carried, so the chunk's NEXT overlay flush re-captures them in full.
        // Without this, an edit to a *different* section after this reload would
        // overwrite the stored overlay with only that section and silently drop
        // these — the same last-write-wins data loss the cumulative capture
        // prevents, just across a reload boundary.
        // (Block entities are immune for free: they reload into the map and the
        // capture always serializes the whole map.) This seeds only the cumulative
        // capture set, never the per-flush gate, so the reload does not itself flush.
        for index in overlay.section_indices() {
            chunk.restore_persist_edited_section(index);
        }
        chunk.clear_dirty();
        chunk.clear_persist_dirty();
        return Ok((chunk, ChunkProvenance::Loaded));
    }

    if has_stored_base {
        // Durable records loaded through an in-memory implementation may still
        // carry the source chunk's transient dirty bits, so normalize them here
        // rather than relying on a particular backend decoder.
        chunk.clear_dirty();
        chunk.clear_persist_dirty();
        Ok((chunk, ChunkProvenance::Loaded))
    } else {
        Ok((chunk, ChunkProvenance::Generated))
    }
}

/// The chunks a shard owns in memory for one world and dimension.
///
/// Construct one with [`LoadedChunkMap::new`], bring chunks in with
/// [`acquire`](Self::acquire), release them with [`release`](Self::release), and
/// drain pending saves with [`take_dirty`](Self::take_dirty). The map owns chunk
/// *data* but never a database handle: every storage call is made through a
/// borrowed [`WorldStore`] passed per acquire.
///
/// # Determinism
///
/// Residency is keyed by [`ChunkPos`] in an ordered [`BTreeMap`], and tickets in
/// an ordered map keyed by [`ChunkTicket`], so iteration order
/// ([`loaded_positions`](Self::loaded_positions), [`take_dirty`](Self::take_dirty))
/// is fully determined by the set of resident chunks — no hashing randomness
/// leaks in. Given the same store contents and the same acquire/release/mutate
/// sequence, the map reaches an identical state and produces identical dirty
/// batches.
#[derive(Debug, Clone)]
pub struct LoadedChunkMap {
    world: WorldId,
    dimension: DimensionId,
    schema_version: SchemaVersion,
    resident: BTreeMap<ChunkPos, ResidentChunk>,
    persist_scan_after: Option<ChunkPos>,
}

impl LoadedChunkMap {
    /// Creates an empty map for `world` / `dimension`, saving chunks under
    /// [`CHUNK_SCHEMA_VERSION`].
    #[must_use]
    pub fn new(world: WorldId, dimension: DimensionId) -> Self {
        Self::with_schema_version(world, dimension, CHUNK_SCHEMA_VERSION)
    }

    /// Creates an empty map for `world` / `dimension` that saves chunks under an
    /// explicit `schema_version`.
    #[must_use]
    pub fn with_schema_version(
        world: WorldId,
        dimension: DimensionId,
        schema_version: SchemaVersion,
    ) -> Self {
        Self {
            world,
            dimension,
            schema_version,
            resident: BTreeMap::new(),
            persist_scan_after: None,
        }
    }

    /// Returns the world these chunks belong to.
    #[must_use]
    pub const fn world(&self) -> WorldId {
        self.world
    }

    /// Returns the dimension these chunks belong to.
    #[must_use]
    pub const fn dimension(&self) -> DimensionId {
        self.dimension
    }

    /// Returns the schema version chunks are saved under.
    #[must_use]
    pub const fn schema_version(&self) -> SchemaVersion {
        self.schema_version
    }

    /// Returns the number of resident chunks.
    #[must_use]
    pub fn loaded_count(&self) -> usize {
        self.resident.len()
    }

    /// Returns `true` if the chunk at `pos` is resident.
    #[must_use]
    pub fn is_loaded(&self, pos: ChunkPos) -> bool {
        self.resident.contains_key(&pos)
    }

    /// Returns the resident chunk positions in ascending order.
    pub fn loaded_positions(&self) -> impl Iterator<Item = ChunkPos> + '_ {
        self.resident.keys().copied()
    }

    /// Returns a shared reference to the resident chunk at `pos`, or `None` if it
    /// is not loaded.
    #[must_use]
    pub fn get(&self, pos: ChunkPos) -> Option<&Chunk> {
        self.resident.get(&pos).map(|r| &r.chunk)
    }

    /// Returns a mutable reference to the resident chunk at `pos`, or `None` if
    /// it is not loaded.
    ///
    /// Mutating through the returned reference (for example
    /// [`Chunk::set_block`](ferrumc_world::Chunk::set_block)) marks the affected
    /// sections dirty, so the chunk is included in the next
    /// [`take_dirty`](Self::take_dirty).
    #[must_use]
    pub fn get_mut(&mut self, pos: ChunkPos) -> Option<&mut Chunk> {
        self.resident.get_mut(&pos).map(|r| &mut r.chunk)
    }

    /// Returns the total number of tickets currently held on `pos` (counting
    /// duplicate holders), or `0` if the chunk is not resident.
    #[must_use]
    pub fn ticket_count(&self, pos: ChunkPos) -> usize {
        self.resident
            .get(&pos)
            .map_or(0, |r| r.tickets.values().sum())
    }

    /// Returns one canonical complete ticket-state record for a resident chunk.
    ///
    /// The test-only record carries world, dimension, chunk position, and every
    /// distinct `(reason, level, holder count)` entry. Ticket entries inherit
    /// the resident map's deterministic [`ChunkTicket`] ordering. `None` means
    /// `pos` is not resident.
    #[cfg(test)]
    pub(crate) fn canonical_ticket_state_record(&self, pos: ChunkPos) -> Option<Vec<u8>> {
        let resident = self.resident.get(&pos)?;
        let mut record = Vec::new();
        record.extend_from_slice(&self.world.get().to_be_bytes());
        record.extend_from_slice(&self.dimension.get().to_be_bytes());
        record.extend_from_slice(&pos.x().to_be_bytes());
        record.extend_from_slice(&pos.z().to_be_bytes());
        record.extend_from_slice(
            &u64::try_from(resident.tickets.len())
                .expect("test ticket entry count fits u64")
                .to_be_bytes(),
        );
        for (ticket, holders) in &resident.tickets {
            let reason = match ticket.reason() {
                TicketReason::Spawn => 0,
                TicketReason::Player => 1,
                TicketReason::Forced => 2,
            };
            record.push(reason);
            record.extend_from_slice(&ticket.level().get().to_be_bytes());
            record.extend_from_slice(
                &u64::try_from(*holders)
                    .expect("test ticket holder count fits u64")
                    .to_be_bytes(),
            );
        }
        Some(record)
    }

    /// Returns the chunk's *effective* (strongest, i.e. lowest) ticket level, or
    /// `None` if it is not resident.
    #[must_use]
    pub fn effective_level(&self, pos: ChunkPos) -> Option<TicketLevel> {
        self.resident
            .get(&pos)
            .and_then(|r| r.tickets.keys().map(|t| t.level()).min())
    }

    /// Builds the storage key for a chunk position in this map's world and
    /// dimension.
    fn chunk_key(&self, pos: ChunkPos) -> ChunkKey {
        ChunkKey::new(self.world, self.dimension, pos)
    }

    /// Ensures the chunk at `pos` is resident and records `ticket` on it.
    ///
    /// If the chunk is already resident, the ticket is simply added and
    /// [`ChunkAcquired::AlreadyResident`] is returned. Otherwise the
    /// load-or-generate flow (see [`load_or_generate`]) brings it into memory
    /// with `ticket` as its first ticket, and
    /// [`ChunkAcquired::NewlyResident`] reports how it was obtained.
    ///
    /// Returns [`SimError::ChunkLoad`] if the store read fails; on failure the
    /// map is left unchanged.
    pub async fn acquire(
        &mut self,
        store: &dyn WorldStore,
        generator: &FlatWorldGenerator,
        pos: ChunkPos,
        ticket: ChunkTicket,
    ) -> SimResult<ChunkAcquired> {
        if let Some(resident) = self.resident.get_mut(&pos) {
            *resident.tickets.entry(ticket).or_insert(0) += 1;
            return Ok(ChunkAcquired::AlreadyResident);
        }

        // Not resident: run the flow before mutating the map so a load failure
        // leaves residency untouched.
        let key = self.chunk_key(pos);
        let (chunk, provenance) = load_or_generate(store, generator, key).await?;
        let mut tickets = BTreeMap::new();
        tickets.insert(ticket, 1usize);
        self.resident.insert(pos, ResidentChunk { chunk, tickets });
        Ok(ChunkAcquired::NewlyResident(provenance))
    }

    /// Acquires every chunk in `spawn` with its spawn ticket, returning the
    /// number that were newly brought into memory.
    ///
    /// Chunks already resident (for any reason) still receive a spawn ticket but
    /// are not counted as newly resident. Returns [`SimError::ChunkLoad`] if any
    /// underlying load fails, after which the chunks acquired so far remain
    /// resident.
    pub async fn acquire_spawn(
        &mut self,
        store: &dyn WorldStore,
        generator: &FlatWorldGenerator,
        spawn: &SpawnChunkTickets,
    ) -> SimResult<usize> {
        let ticket = spawn.ticket();
        let mut newly_resident = 0;
        for pos in spawn.positions() {
            if self
                .acquire(store, generator, pos, ticket)
                .await?
                .is_newly_resident()
            {
                newly_resident += 1;
            }
        }
        Ok(newly_resident)
    }

    /// Releases one `ticket` from the chunk at `pos`.
    ///
    /// Decrements that ticket's holder count. If it was the chunk's last ticket
    /// the chunk is unloaded ([`TicketRelease::Unloaded`]). Persistence is not
    /// surfaced here: the caller captures any pending player edits via
    /// [`take_persist_dirty`](Self::take_persist_dirty) before releasing, so an
    /// unloaded chunk has nothing left to save and a generated-only chunk costs
    /// no storage. Releasing a ticket that is not held (or a chunk that is not
    /// resident) is a no-op reported as [`TicketRelease::NotPresent`].
    pub fn release(&mut self, pos: ChunkPos, ticket: ChunkTicket) -> TicketRelease {
        let Some(resident) = self.resident.get_mut(&pos) else {
            return TicketRelease::NotPresent;
        };
        let Entry::Occupied(mut entry) = resident.tickets.entry(ticket) else {
            return TicketRelease::NotPresent;
        };
        let count = entry.get_mut();
        *count -= 1;
        if *count == 0 {
            entry.remove();
        }
        if !resident.tickets.is_empty() {
            return TicketRelease::StillLoaded;
        }

        // Last ticket gone: unload and drop the chunk.
        match self.resident.remove(&pos) {
            Some(_) => TicketRelease::Unloaded,
            // `pos` was present at the start of the method and only this `&mut`
            // path could have removed it, so this arm is unreachable; report it
            // as a no-op rather than panicking.
            None => TicketRelease::NotPresent,
        }
    }

    /// Collects every resident chunk with unsaved changes as a save batch and
    /// marks those chunks clean.
    ///
    /// Each returned `(ChunkKey, ChunkRecord)` is a snapshot ready to hand to
    /// [`WorldStore::save_chunks`]. The chunks' dirty flags are cleared here on
    /// the assumption the batch will be persisted; this method does not perform
    /// the save and intentionally implements no flush *policy* (when to call it,
    /// and what to do if the save later fails, are the caller's concern). The
    /// batch is ordered by [`ChunkPos`] for determinism.
    #[must_use]
    pub fn take_dirty(&mut self) -> Vec<(ChunkKey, ChunkRecord)> {
        let world = self.world;
        let dimension = self.dimension;
        let schema = self.schema_version;
        let mut batch = Vec::new();
        for (&pos, resident) in &mut self.resident {
            if resident.chunk.dirty_sections().any() {
                resident.chunk.clear_dirty();
                batch.push((
                    ChunkKey::new(world, dimension, pos),
                    ChunkRecord::new(schema, resident.chunk.clone()),
                ));
            }
        }
        batch
    }

    /// Returns `true` if any resident chunk has unsaved gameplay edits.
    ///
    /// A cheap pre-check for the flush hot path: the driver only reserves a
    /// storage-channel slot when there is something to persist.
    #[must_use]
    pub fn has_persist_dirty(&self) -> bool {
        self.resident
            .values()
            .any(|resident| resident.chunk.persist_dirty_sections().any())
    }

    /// Collects an overlay record for every resident chunk with unsaved gameplay
    /// edits and clears those chunks' persist-dirty masks.
    ///
    /// This is the persistence handoff: unlike [`take_dirty`](Self::take_dirty)
    /// (which emits a full [`ChunkRecord`] for any network-dirty chunk, including
    /// a freshly generated one), this emits a [`ChunkOverlayRecord`] carrying every
    /// section a gameplay edit has ever touched (the chunk's cumulative persist-edited
    /// set), gated on the per-flush persist-dirty signal. Capturing the cumulative set
    /// on each flush keeps the store's last-write-wins overwrite a complete snapshot,
    /// so edits to different sections on different flush ticks are not lost on reload.
    /// A generated-but-never-edited chunk has an empty persist-dirty mask and so is
    /// **never** included, which is what keeps untouched terrain at zero storage.
    /// Each overlay is stamped with `tick` as its capture time and
    /// [`OVERLAY_SCHEMA_VERSION`]. The batch is ordered by [`ChunkPos`] for
    /// determinism. As with `take_dirty`, this captures and clears but does not
    /// itself persist — flush *policy* is the caller's. This legacy public path
    /// retains its complete-drain behavior; the scheduler uses the separately
    /// bounded internal variant.
    #[must_use]
    pub fn take_persist_dirty(&mut self, tick: u64) -> Vec<(ChunkKey, ChunkOverlayRecord)> {
        let batch = self.take_persist_dirty_up_to(tick, usize::MAX);
        self.persist_scan_after = None;
        batch
    }

    /// Collects at most `capacity` persist-dirty overlays in deterministic
    /// chunk order.
    ///
    /// Only records transferred into the returned vector have their per-flush
    /// dirty masks cleared. A deterministic continuation cursor visits the
    /// deferred tail before wrapping to lower keys, so repeatedly re-dirtying a
    /// low chunk cannot starve older work. Returned records remain sorted by
    /// chunk position even when selection wraps.
    pub(crate) fn take_persist_dirty_bounded(
        &mut self,
        tick: u64,
        capacity: NonZeroUsize,
    ) -> Vec<(ChunkKey, ChunkOverlayRecord)> {
        let capacity = capacity.get();
        let world = self.world;
        let dimension = self.dimension;
        let mut batch = Vec::with_capacity(capacity.min(self.resident.len()));
        let mut last_selected = None;

        if let Some(after) = self.persist_scan_after {
            for (&pos, resident) in self.resident.range_mut((Excluded(after), Unbounded)) {
                if batch.len() >= capacity {
                    break;
                }
                if let Some(record) =
                    Self::take_persist_record(world, dimension, tick, pos, resident)
                {
                    batch.push(record);
                    last_selected = Some(pos);
                }
            }
            if batch.len() < capacity {
                for (&pos, resident) in self.resident.range_mut(..=after) {
                    if batch.len() >= capacity {
                        break;
                    }
                    if let Some(record) =
                        Self::take_persist_record(world, dimension, tick, pos, resident)
                    {
                        batch.push(record);
                        last_selected = Some(pos);
                    }
                }
            }
        } else {
            for (&pos, resident) in &mut self.resident {
                if batch.len() >= capacity {
                    break;
                }
                if let Some(record) =
                    Self::take_persist_record(world, dimension, tick, pos, resident)
                {
                    batch.push(record);
                    last_selected = Some(pos);
                }
            }
        }

        self.persist_scan_after = if self.has_persist_dirty() {
            last_selected
        } else {
            None
        };
        batch.sort_unstable_by_key(|(key, _)| key.pos());
        batch
    }

    /// Shared deterministic persist capture with an explicit record ceiling.
    fn take_persist_dirty_up_to(
        &mut self,
        tick: u64,
        capacity: usize,
    ) -> Vec<(ChunkKey, ChunkOverlayRecord)> {
        let world = self.world;
        let dimension = self.dimension;
        let mut batch = Vec::with_capacity(capacity.min(self.resident.len()));
        for (&pos, resident) in &mut self.resident {
            if batch.len() >= capacity {
                break;
            }
            if let Some(record) = Self::take_persist_record(world, dimension, tick, pos, resident) {
                batch.push(record);
            }
        }
        batch
    }

    /// Captures one dirty resident and clears only the transferred flush mask.
    fn take_persist_record(
        world: WorldId,
        dimension: DimensionId,
        tick: u64,
        pos: ChunkPos,
        resident: &mut ResidentChunk,
    ) -> Option<(ChunkKey, ChunkOverlayRecord)> {
        if !resident.chunk.persist_dirty_sections().any() {
            return None;
        }
        let record =
            ChunkOverlayRecord::from_chunk(OVERLAY_SCHEMA_VERSION, pos, &resident.chunk, tick);
        resident.chunk.clear_persist_dirty();
        Some((ChunkKey::new(world, dimension, pos), record))
    }
}

#[cfg(test)]
mod tests {
    use ferrumc_core::{DimensionId, WorldId};
    use ferrumc_math::BlockPos;
    use ferrumc_storage::{ChunkKey, ChunkRecord, InMemoryStore, SchemaVersion, WorldStore};
    use ferrumc_world::{BlockStateId, Chunk};

    use super::*;
    use crate::ticket::{ChunkTicket, TicketReason};

    fn world() -> WorldId {
        WorldId::new(0)
    }

    fn dimension() -> DimensionId {
        DimensionId::new(0)
    }

    fn map() -> LoadedChunkMap {
        LoadedChunkMap::new(world(), dimension())
    }

    fn gen() -> FlatWorldGenerator {
        FlatWorldGenerator::new()
    }

    fn spawn_ticket() -> ChunkTicket {
        ChunkTicket::of(TicketReason::Spawn)
    }

    /// A clean (already-persisted) chunk carrying a single marker block, used to
    /// prove a load returns stored data rather than freshly generated terrain.
    fn marker_chunk(pos: ChunkPos, marker: BlockPos, state: BlockStateId) -> Chunk {
        let mut chunk = Chunk::new(pos);
        chunk.set_block(marker, state).expect("marker in chunk");
        chunk.clear_dirty();
        chunk
    }

    #[tokio::test]
    async fn acquire_miss_generates_hit_loads() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);

        // Empty store -> generate.
        let mut m = map();
        let outcome = m
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        assert_eq!(outcome.provenance(), Some(ChunkProvenance::Generated));
        // Generated flat terrain has a grass surface at y = 63.
        let surface = m
            .get(pos)
            .and_then(|c| c.get_block(BlockPos::new(0, 63, 0)))
            .expect("surface block");
        assert_ne!(surface, BlockStateId::AIR);

        // Pre-populate a *different* chunk and load it from a fresh map.
        let marker = BlockPos::new(1, 64, 1);
        let stored = marker_chunk(pos, marker, BlockStateId::new(7));
        let key = ChunkKey::new(world(), dimension(), pos);
        store
            .save_chunk(key, ChunkRecord::new(SchemaVersion::new(9), stored))
            .await
            .expect("save");

        let mut m2 = map();
        let outcome = m2
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        assert_eq!(outcome.provenance(), Some(ChunkProvenance::Loaded));
        // The loaded chunk is the stored one: marker present, no generated grass.
        let loaded = m2.get(pos).expect("resident");
        assert_eq!(loaded.get_block(marker), Some(BlockStateId::new(7)));
        assert_eq!(
            loaded.get_block(BlockPos::new(0, 63, 0)),
            Some(BlockStateId::AIR),
            "loaded chunk must not be regenerated"
        );
    }

    #[tokio::test]
    async fn second_acquire_is_already_resident() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(2, -1);
        let mut m = map();

        assert!(m
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("first")
            .is_newly_resident());
        let second = m
            .acquire(
                &store,
                &generator,
                pos,
                ChunkTicket::of(TicketReason::Player),
            )
            .await
            .expect("second");
        assert!(second.is_already_resident());
        assert_eq!(m.loaded_count(), 1);
        assert_eq!(m.ticket_count(pos), 2);
        // Effective level is the stronger (lower) of the two tickets.
        assert_eq!(m.effective_level(pos), Some(TicketLevel::ENTITY_TICKING));
    }

    #[tokio::test]
    async fn tickets_govern_the_loaded_set() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);
        let mut m = map();
        let ticket = spawn_ticket();

        assert!(!m.is_loaded(pos));
        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire");
        // Add a duplicate holder of the same ticket.
        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire dup");
        assert!(m.is_loaded(pos));
        assert_eq!(m.ticket_count(pos), 2);

        // First release: one duplicate holder remains, chunk stays loaded.
        assert!(m.release(pos, ticket).is_still_loaded());
        assert!(m.is_loaded(pos));

        // Second release: last ticket gone, chunk unloads.
        let release = m.release(pos, ticket);
        assert!(release.is_unloaded());
        assert!(!m.is_loaded(pos));
        assert_eq!(m.loaded_count(), 0);
    }

    #[tokio::test]
    async fn release_unknown_ticket_or_chunk_is_noop() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(5, 5);
        let mut m = map();

        // No chunk at all.
        assert!(m.release(pos, spawn_ticket()).is_not_present());

        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // A ticket the chunk does not hold.
        assert!(m
            .release(pos, ChunkTicket::of(TicketReason::Forced))
            .is_not_present());
        assert!(m.is_loaded(pos), "no-op release keeps the chunk loaded");
    }

    #[tokio::test]
    async fn dirty_chunks_collected_on_mutation() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(0, 0);

        // Start from a clean, previously-saved chunk so dirtiness comes purely
        // from our mutation.
        let key = ChunkKey::new(world(), dimension(), pos);
        store
            .save_chunk(
                key,
                ChunkRecord::new(
                    SchemaVersion::new(1),
                    marker_chunk(pos, BlockPos::new(0, 0, 0), BlockStateId::new(1)),
                ),
            )
            .await
            .expect("save");

        let mut m = map();
        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // Freshly loaded clean chunk: nothing dirty.
        assert!(m.take_dirty().is_empty());

        // Mutate it.
        m.get_mut(pos)
            .expect("resident")
            .set_block(BlockPos::new(2, 70, 2), BlockStateId::new(5))
            .expect("in range");

        let dirty = m.take_dirty();
        assert_eq!(dirty.len(), 1);
        assert_eq!(dirty[0].0, key);
        // Draining clears dirtiness: a second take yields nothing.
        assert!(m.take_dirty().is_empty());
    }

    #[tokio::test]
    async fn generated_chunk_is_dirty_for_initial_save() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(3, 4);
        let mut m = map();

        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // A freshly generated chunk has filled sections and so is dirty: it must
        // be handed off for its first save.
        let dirty = m.take_dirty();
        assert_eq!(dirty.len(), 1);
        assert_eq!(dirty[0].0, ChunkKey::new(world(), dimension(), pos));
    }

    #[tokio::test]
    async fn unloading_generated_chunk_yields_no_overlay() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(1, 1);
        let mut m = map();
        let ticket = spawn_ticket();

        m.acquire(&store, &generator, pos, ticket)
            .await
            .expect("acquire");
        // A freshly generated, never-edited chunk has an empty persist-dirty mask,
        // so it produces NO overlay and costs zero storage even on unload.
        assert!(!m.has_persist_dirty());
        assert!(m.take_persist_dirty(0).is_empty());
        assert!(m.release(pos, ticket).is_unloaded());
        assert!(!m.is_loaded(pos));
    }

    #[tokio::test]
    async fn take_persist_dirty_collects_only_player_marked_chunks() {
        let store = InMemoryStore::new();
        let generator = gen();
        let edited = ChunkPos::new(0, 0);
        let untouched = ChunkPos::new(1, 0);
        let mut m = map();

        m.acquire(&store, &generator, edited, spawn_ticket())
            .await
            .expect("acquire edited");
        m.acquire(&store, &generator, untouched, spawn_ticket())
            .await
            .expect("acquire untouched");

        // Nothing is persist-dirty yet, even though both are freshly generated
        // (and therefore network-dirty).
        assert!(!m.has_persist_dirty());
        assert!(m.take_persist_dirty(5).is_empty());

        // Simulate a gameplay edit: mark a section persist-dirty (the sim layer's
        // job) on exactly one chunk.
        let target = BlockPos::new(2, 70, 2);
        m.get_mut(edited)
            .expect("resident")
            .set_block(target, BlockStateId::new(5))
            .expect("in range");
        m.get_mut(edited)
            .expect("resident")
            .mark_persist_dirty(target);

        assert!(m.has_persist_dirty());
        let overlays = m.take_persist_dirty(7);
        assert_eq!(
            overlays.len(),
            1,
            "only the player-edited chunk is captured"
        );
        assert_eq!(overlays[0].0, ChunkKey::new(world(), dimension(), edited));
        assert_eq!(overlays[0].1.updated_at_tick(), 7);
        assert_eq!(overlays[0].1.schema_version(), OVERLAY_SCHEMA_VERSION);
        // Draining cleared the persist mask: a second take yields nothing.
        assert!(m.take_persist_dirty(8).is_empty());
    }

    #[tokio::test]
    async fn overlay_round_trips_through_store_reload() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(3, -1);
        let key = ChunkKey::new(world(), dimension(), pos);
        let mut m = map();

        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");
        // Break the grass surface and persist the overlay.
        let surface = pos.origin_block(63);
        {
            let chunk = m.get_mut(pos).expect("resident");
            chunk
                .set_block(surface, BlockStateId::AIR)
                .expect("in range");
            chunk.mark_persist_dirty(surface);
        }
        let overlays = m.take_persist_dirty(1);
        store.save_chunk_overlays(overlays).await.expect("persist");

        // A fresh map loading the same key reconstructs the edit over a baseline.
        let mut m2 = map();
        let outcome = m2
            .acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire reload");
        assert_eq!(outcome.provenance(), Some(ChunkProvenance::Loaded));
        let reloaded = m2.get(pos).expect("resident");
        assert_eq!(reloaded.get_block(surface), Some(BlockStateId::AIR));
        // A loaded chunk is clean: it is not immediately re-persisted.
        assert!(!reloaded.persist_dirty_sections().any());
        let _ = key;
    }

    #[tokio::test]
    async fn two_sections_edited_on_separate_flush_ticks_both_survive_reload() {
        // Regression for the overlay last-write-wins data-loss bug: editing two
        // DIFFERENT sections of ONE chunk on DIFFERENT flush ticks must not let the
        // later flush overwrite the earlier section away. `InMemoryStore` overwrites
        // per key (like redb), so correctness rests on each flush capturing the full
        // cumulative set of edited sections.
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(4, -2);
        let mut m = map();
        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");

        // Edit 1: break the grass surface at y=63 (section 7) and flush on tick 1.
        let dug = pos.origin_block(63);
        {
            let chunk = m.get_mut(pos).expect("resident");
            chunk.set_block(dug, BlockStateId::AIR).expect("in range");
            chunk.mark_persist_dirty(dug);
        }
        store
            .save_chunk_overlays(m.take_persist_dirty(1))
            .await
            .expect("flush 1");

        // Edit 2: place stone at y=70 (section 8) and flush on a LATER tick.
        let placed = pos.origin_block(70);
        {
            let chunk = m.get_mut(pos).expect("resident");
            chunk
                .set_block(placed, BlockStateId::new(1))
                .expect("in range");
            chunk.mark_persist_dirty(placed);
        }
        store
            .save_chunk_overlays(m.take_persist_dirty(2))
            .await
            .expect("flush 2");

        // Reload from a fresh map: BOTH edits must survive (the dug hole did not
        // revert to the baseline grass when the second flush overwrote the overlay).
        let mut m2 = map();
        m2.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("reload");
        let reloaded = m2.get(pos).expect("resident");
        assert_eq!(
            reloaded.get_block(dug),
            Some(BlockStateId::AIR),
            "section 7 edit (the dug hole) must survive the second flush's overwrite",
        );
        assert_eq!(
            reloaded.get_block(placed),
            Some(BlockStateId::new(1)),
            "section 8 edit (the placed stone) must survive",
        );
    }

    #[tokio::test]
    async fn edit_after_reload_does_not_overwrite_a_previously_persisted_section() {
        // The cumulative set must also survive a reload boundary: edit section A,
        // flush, reload; then edit a DIFFERENT section B, flush, reload. Because the
        // load path reseeds the cumulative persist-edited set from the loaded
        // overlay's sections, the second flush re-captures BOTH sections rather than
        // overwriting A away — matching the always-whole block-entity capture.
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(-5, 6);
        let dug = pos.origin_block(63); // section 7
        let placed = pos.origin_block(70); // section 8

        // Session 1: edit section 7, flush, end session.
        {
            let mut m = map();
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire s1");
            let chunk = m.get_mut(pos).expect("resident");
            chunk.set_block(dug, BlockStateId::AIR).expect("in range");
            chunk.mark_persist_dirty(dug);
            store
                .save_chunk_overlays(m.take_persist_dirty(1))
                .await
                .expect("flush s1");
        }

        // Session 2: reload (seeds the cumulative set), edit section 8, flush.
        {
            let mut m = map();
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire s2");
            // The reseed must NOT itself mark the chunk for a flush: a freshly
            // reloaded, unedited chunk is still clean.
            assert!(!m.has_persist_dirty());
            let chunk = m.get_mut(pos).expect("resident");
            chunk
                .set_block(placed, BlockStateId::new(1))
                .expect("in range");
            chunk.mark_persist_dirty(placed);
            store
                .save_chunk_overlays(m.take_persist_dirty(2))
                .await
                .expect("flush s2");
        }

        // Session 3: reload and assert BOTH the pre- and post-reload edits survive.
        let mut m3 = map();
        m3.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire s3");
        let reloaded = m3.get(pos).expect("resident");
        assert_eq!(
            reloaded.get_block(dug),
            Some(BlockStateId::AIR),
            "the section edited BEFORE the reload must not be overwritten by a later flush",
        );
        assert_eq!(
            reloaded.get_block(placed),
            Some(BlockStateId::new(1)),
            "the section edited AFTER the reload must survive",
        );
    }

    #[tokio::test]
    async fn three_sections_edited_across_three_flushes_and_a_reload_all_survive() {
        // Extends the two-section regressions to three sections over three flush
        // ticks with an unload/reload in the middle, exercising the cumulative
        // capture and the load-path reseed together: every ever-edited section must
        // be present after the final reload, not just the two most recent.
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(3, -7);
        let s4 = pos.origin_block(5); // section 4 (below the flat surface, so solid)
        let s8 = pos.origin_block(70); // section 8 (above the surface, so air)
        let s12 = pos.origin_block(130); // section 12 (above the surface, so air)

        // Session 1: edit section 4 then section 8, flushing each on its own tick.
        {
            let mut m = map();
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire s1");
            {
                let chunk = m.get_mut(pos).expect("resident");
                chunk.set_block(s4, BlockStateId::AIR).expect("in range");
                chunk.mark_persist_dirty(s4);
            }
            store
                .save_chunk_overlays(m.take_persist_dirty(1))
                .await
                .expect("flush 1");
            {
                let chunk = m.get_mut(pos).expect("resident");
                chunk.set_block(s8, BlockStateId::new(1)).expect("in range");
                chunk.mark_persist_dirty(s8);
            }
            store
                .save_chunk_overlays(m.take_persist_dirty(2))
                .await
                .expect("flush 2");
        }

        // Session 2: reload (reseeds the cumulative set with {4, 8}), edit a third
        // section, flush. The reseed must keep the earlier two from being dropped.
        {
            let mut m = map();
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire s2");
            assert!(
                !m.has_persist_dirty(),
                "the reseed must not arm the flush gate"
            );
            {
                let chunk = m.get_mut(pos).expect("resident");
                chunk
                    .set_block(s12, BlockStateId::new(1))
                    .expect("in range");
                chunk.mark_persist_dirty(s12);
            }
            store
                .save_chunk_overlays(m.take_persist_dirty(3))
                .await
                .expect("flush 3");
        }

        // Session 3: reload and assert ALL THREE edits survive.
        let mut m3 = map();
        m3.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire s3");
        let reloaded = m3.get(pos).expect("resident");
        assert_eq!(
            reloaded.get_block(s4),
            Some(BlockStateId::AIR),
            "section 4 (first flush, before the reload) must survive",
        );
        assert_eq!(
            reloaded.get_block(s8),
            Some(BlockStateId::new(1)),
            "section 8 (second flush, before the reload) must survive",
        );
        assert_eq!(
            reloaded.get_block(s12),
            Some(BlockStateId::new(1)),
            "section 12 (third flush, after the reload) must survive",
        );
    }

    #[tokio::test]
    async fn block_entities_round_trip_through_store_reload() {
        use ferrumc_items::{ComponentPatch, ItemId, ItemStack};
        use ferrumc_math::BlockPos;
        use ferrumc_world::{BlockEntity, ChestInventory, Sign, SignKind};
        use std::num::NonZeroU8;

        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(2, 2);
        let mut m = map();
        m.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("acquire");

        // A sign with text and a chest holding a stack, both at in-chunk positions.
        let sign_pos = pos.origin_block(64);
        let chest_pos = BlockPos::new(sign_pos.x() + 1, 70, sign_pos.z() + 1);
        let lines = [
            "first".to_owned(),
            "second".to_owned(),
            String::new(),
            "fourth".to_owned(),
        ];
        let mut sign = Sign::new(SignKind::Sign);
        sign.set_face_lines(true, lines.clone());
        let mut chest = ChestInventory::new();
        *chest.slot_mut(5).expect("slot 5") = ItemStack::new(
            ItemId::from_name("diamond").expect("diamond in registry"),
            NonZeroU8::new(17).expect("non-zero"),
            ComponentPatch::empty(),
        );
        {
            let chunk = m.get_mut(pos).expect("resident");
            chunk
                .set_block_entity(sign_pos, BlockEntity::Sign(sign.clone()))
                .expect("set sign");
            chunk
                .set_block_entity(chest_pos, BlockEntity::Chest(chest.clone()))
                .expect("set chest");
            // A block-entity edit marks its section persist-dirty (mirroring the sim
            // shard's sign/chest handlers), so an overlay is emitted.
            chunk.mark_persist_dirty(sign_pos);
        }
        let overlays = m.take_persist_dirty(1);
        store.save_chunk_overlays(overlays).await.expect("persist");

        // A fresh map reloads the chunk and reconstructs BOTH block entities with
        // their exact contents (sign text restored; chest item id + count conserved).
        let mut m2 = map();
        m2.acquire(&store, &generator, pos, spawn_ticket())
            .await
            .expect("reload");
        let reloaded = m2.get(pos).expect("resident");
        assert_eq!(
            reloaded.block_entity(sign_pos),
            Some(&BlockEntity::Sign(sign))
        );
        assert_eq!(
            reloaded.block_entity(chest_pos),
            Some(&BlockEntity::Chest(chest))
        );
    }

    #[tokio::test]
    async fn acquire_spawn_loads_the_whole_set() {
        let store = InMemoryStore::new();
        let generator = gen();
        let spawn = SpawnChunkTickets::new(ChunkPos::new(0, 0), 1);
        let mut m = map();

        let newly = m
            .acquire_spawn(&store, &generator, &spawn)
            .await
            .expect("acquire_spawn");
        assert_eq!(newly, 9);
        assert_eq!(m.loaded_count(), 9);
        for pos in spawn.positions() {
            assert!(m.is_loaded(pos));
            assert_eq!(m.effective_level(pos), Some(TicketLevel::TICKING));
        }
    }

    #[tokio::test]
    async fn free_load_or_generate_reports_provenance() {
        let store = InMemoryStore::new();
        let generator = gen();
        let pos = ChunkPos::new(8, 8);
        let key = ChunkKey::new(world(), dimension(), pos);

        // Miss -> generate the requested position.
        let (chunk, prov) = load_or_generate(&store, &generator, key)
            .await
            .expect("generate path");
        assert!(prov.is_generated());
        assert_eq!(chunk.pos(), pos);

        // Hit -> return the stored chunk.
        store
            .save_chunk(key, ChunkRecord::new(SchemaVersion::new(1), chunk))
            .await
            .expect("save");
        let (_, prov) = load_or_generate(&store, &generator, key)
            .await
            .expect("load path");
        assert!(prov.is_loaded());
    }

    #[tokio::test]
    async fn loaded_positions_are_sorted_and_deterministic() {
        let store = InMemoryStore::new();
        let generator = gen();
        let mut m = map();
        for pos in [
            ChunkPos::new(2, 0),
            ChunkPos::new(-1, 3),
            ChunkPos::new(0, 0),
        ] {
            m.acquire(&store, &generator, pos, spawn_ticket())
                .await
                .expect("acquire");
        }
        let order: Vec<ChunkPos> = m.loaded_positions().collect();
        assert_eq!(
            order,
            vec![
                ChunkPos::new(-1, 3),
                ChunkPos::new(0, 0),
                ChunkPos::new(2, 0),
            ]
        );
    }
}
