//! Item registry lookups for Minecraft 1.21.8.
//!
//! The backing tables (`ITEM_NAMES`, `ITEM_MAX_STACK`, `ITEM_BY_NAME`,
//! `ITEM_TO_BLOCK`) are generated at build time from the vendored
//! `data/items.json` and `data/item_to_block_mapping.json` snapshots (see
//! `build.rs`) and `include!`d here. The runtime therefore does no JSON parsing
//! and pays zero boot cost: every lookup is either a direct index or a
//! `binary_search` over a sorted static array.
//!
//! Item ids are the protocol item ids for 1.21.8 (contiguous `0..=N`). Names are
//! the canonical namespaced resource locations (e.g. `"minecraft:stone"`), but
//! the name lookup also accepts the bare form (`"stone"`) for convenience,
//! mirroring [`crate::default_block_state_id`].

// The generated tables: ITEM_COUNT, ITEM_NAMES, ITEM_MAX_STACK, ITEM_BY_NAME,
// ITEM_TO_BLOCK. Generated by build.rs from the vendored data/ snapshots.
include!(concat!(env!("OUT_DIR"), "/items_generated.rs"));

/// The default maximum stack size for an item whose id is not in the registry.
///
/// Real items always have an explicit `max_stack_size`; this only applies to
/// out-of-range ids and matches the vanilla fallback of 64.
pub const DEFAULT_MAX_STACK: u8 = 64;

/// Resolves an item resource location to its protocol item id, or `None` if the
/// name is unknown.
///
/// Both the canonical namespaced form (`"minecraft:stone"`) and the bare form
/// (`"stone"`) resolve to the same id; any other namespace is rejected.
///
/// # Examples
///
/// ```
/// use ferrumc_registry::item::lookup_item_protocol_id;
///
/// assert_eq!(lookup_item_protocol_id("minecraft:stone"), Some(1));
/// assert_eq!(lookup_item_protocol_id("stone"), Some(1));
/// assert_eq!(lookup_item_protocol_id("notch:stone"), None);
/// ```
#[must_use]
pub fn lookup_item_protocol_id(name: &str) -> Option<i32> {
    // Accept the bare form by canonicalizing to the namespaced key the table
    // stores. A non-`minecraft:` namespace can never match.
    let bare = name.strip_prefix("minecraft:").unwrap_or(name);
    if bare.contains(':') {
        return None;
    }
    let mut buf = String::with_capacity("minecraft:".len() + bare.len());
    buf.push_str("minecraft:");
    buf.push_str(bare);
    ITEM_BY_NAME
        .binary_search_by(|(candidate, _)| (*candidate).cmp(buf.as_str()))
        .ok()
        .map(|idx| ITEM_BY_NAME[idx].1)
}

/// Resolves a protocol item id to its canonical namespaced name, or `None` if
/// the id is out of range.
///
/// # Examples
///
/// ```
/// use ferrumc_registry::item::lookup_item_name;
///
/// assert_eq!(lookup_item_name(1), Some("minecraft:stone"));
/// assert_eq!(lookup_item_name(-1), None);
/// ```
#[must_use]
pub fn lookup_item_name(id: i32) -> Option<&'static str> {
    let idx = usize::try_from(id).ok()?;
    ITEM_NAMES.get(idx).copied()
}

/// Returns the maximum stack size for an item id.
///
/// Returns the registry value for a known id. For an out-of-range id it returns
/// [`DEFAULT_MAX_STACK`] (64) rather than failing, so callers can clamp counts
/// without a prior existence check; use [`lookup_item_name`] to test existence.
///
/// # Examples
///
/// ```
/// use ferrumc_registry::item::item_max_stack;
///
/// assert_eq!(item_max_stack(1), 64); // stone
/// assert_eq!(item_max_stack(895), 1); // diamond_sword
/// ```
#[must_use]
pub fn item_max_stack(id: i32) -> u8 {
    match usize::try_from(id) {
        Ok(idx) => ITEM_MAX_STACK
            .get(idx)
            .copied()
            .unwrap_or(DEFAULT_MAX_STACK),
        Err(_) => DEFAULT_MAX_STACK,
    }
}

/// Returns the block-state id the item places, or `None` if the item is not a
/// placeable block.
///
/// The mapping is taken verbatim from the vendored snapshot. Note that
/// `minecraft:air` (item id 0) maps to block-state 0 in the data; callers that
/// treat air as non-placeable must special-case it themselves rather than
/// relying on this returning `None`.
///
/// # Examples
///
/// ```
/// use ferrumc_registry::item::item_to_block_state;
///
/// assert_eq!(item_to_block_state(1), Some(1)); // stone
/// assert_eq!(item_to_block_state(895), None); // diamond_sword: not a block
/// ```
#[must_use]
pub fn item_to_block_state(id: i32) -> Option<u32> {
    ITEM_TO_BLOCK
        .binary_search_by_key(&id, |(item_id, _)| *item_id)
        .ok()
        .map(|idx| ITEM_TO_BLOCK[idx].1)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    use super::{
        item_max_stack, item_to_block_state, lookup_item_name, lookup_item_protocol_id, ITEM_COUNT,
    };

    /// Absolute path to a vendored item-data file in this crate's `data/` dir.
    fn data(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("data")
            .join(name)
    }

    #[test]
    fn known_item_ids_resolve_both_directions() {
        // A handful of well-known items pinned against the snapshot.
        for (name, id) in [
            ("stone", 1),
            ("dirt", 28),
            ("oak_planks", 36),
            ("glass", 195),
            ("diamond_sword", 895),
        ] {
            assert_eq!(lookup_item_protocol_id(name), Some(id), "bare {name}");
            assert_eq!(
                lookup_item_protocol_id(&format!("minecraft:{name}")),
                Some(id),
                "namespaced {name}"
            );
            assert_eq!(
                lookup_item_name(id),
                Some(format!("minecraft:{name}").as_str())
            );
        }
    }

    #[test]
    fn max_stack_values_match_snapshot() {
        assert_eq!(item_max_stack(1), 64); // stone
        assert_eq!(item_max_stack(895), 1); // diamond_sword (has max_damage)
                                            // Out-of-range ids fall back to the vanilla default.
        assert_eq!(item_max_stack(-1), super::DEFAULT_MAX_STACK);
        assert_eq!(item_max_stack(i32::MAX), super::DEFAULT_MAX_STACK);
    }

    #[test]
    fn block_state_mapping_matches_snapshot() {
        assert_eq!(item_to_block_state(1), Some(1)); // stone
        assert_eq!(item_to_block_state(28), Some(10)); // dirt
        assert_eq!(item_to_block_state(36), Some(15)); // oak_planks
        assert_eq!(item_to_block_state(195), Some(562)); // glass
        assert_eq!(item_to_block_state(895), None); // diamond_sword: not a block
        assert_eq!(item_to_block_state(0), Some(0)); // air maps to block-state 0
    }

    #[test]
    fn unknown_and_malformed_names_are_rejected() {
        assert_eq!(lookup_item_protocol_id(""), None);
        assert_eq!(lookup_item_protocol_id("minecraft:"), None);
        assert_eq!(lookup_item_protocol_id("STONE"), None); // case-sensitive
        assert_eq!(lookup_item_protocol_id("notch:stone"), None); // wrong namespace
        assert_eq!(lookup_item_protocol_id("definitely_not_an_item"), None);
    }

    /// Drift guard: re-parse the vendored `items.json` and confirm the generated
    /// tables still agree with the real data for the pinned sample, plus the
    /// item count.
    #[test]
    fn generated_tables_match_vendored_items_json() {
        #[derive(serde::Deserialize)]
        struct RawItem {
            id: i32,
            components: RawComponents,
        }
        #[derive(serde::Deserialize)]
        struct RawComponents {
            #[serde(rename = "minecraft:max_stack_size")]
            max_stack_size: Option<i64>,
        }

        let raw =
            std::fs::read_to_string(data("items.json")).expect("vendored items.json must exist");
        let items: BTreeMap<String, RawItem> =
            serde_json::from_str(&raw).expect("items.json must parse");

        assert_eq!(items.len(), ITEM_COUNT, "item count drift");

        for (name, item) in &items {
            assert_eq!(
                lookup_item_protocol_id(name),
                Some(item.id),
                "id drift for {name}"
            );
            assert_eq!(
                lookup_item_name(item.id),
                Some(format!("minecraft:{name}").as_str()),
                "name drift for id {}",
                item.id
            );
            let expected = u8::try_from(item.components.max_stack_size.unwrap()).unwrap();
            assert_eq!(
                item_max_stack(item.id),
                expected,
                "max_stack drift for {name}"
            );
        }
    }

    /// Drift guard: re-parse the vendored mapping and confirm the generated
    /// item -> block-state table agrees for every entry.
    #[test]
    fn generated_block_table_matches_vendored_mapping() {
        let raw = std::fs::read_to_string(data("item_to_block_mapping.json"))
            .expect("vendored item_to_block_mapping.json must exist");
        let mapping: BTreeMap<String, String> =
            serde_json::from_str(&raw).expect("mapping must parse");

        for (k, v) in &mapping {
            let item_id: i32 = k.parse().unwrap();
            let block_state: u32 = v.parse().unwrap();
            assert_eq!(
                item_to_block_state(item_id),
                Some(block_state),
                "block-state drift for item {item_id}"
            );
        }
    }
}
